#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Causal 1m ICT-style sweep -> MSS/displacement -> FVG-limit research.

The study deliberately uses only the OHLC columns returned by the existing
``OKXTradeBarLoader``.  Higher timeframes are resampled from that same 1m
stream, so there is one primary execution clock and no independently fetched
higher-timeframe data.

Mechanical definitions (frozen before the run)
-----------------------------------------------
* Liquidity: first sweep of a causally-confirmed 15m/30m/1h/4h swing high/low.
  A swing uses a symmetric ``width`` window and is available only after all
  right-hand candles have closed.
* Long setup: a first sweep below one or more active higher-timeframe swing
  lows, followed within 60 minutes by a 1m bearish-context MSS.  The MSS must
  close above the prior confirmed micro swing high with a displacement body.
  Short setups mirror this rule.
* FVG: the candle after the displacement creates a three-candle gap.  The long
  limit is the next candle's low (the upper FVG edge); the short limit is its
  high (the lower FVG edge).  The order becomes eligible only on the following
  1m bar.
* Stop: the most extreme price from the liquidity sweep through FVG
  confirmation.  A same-bar TP/SL collision is marked as a stop first.

This is research code, not a live trading implementation.  It writes an audit
trail, parameter sensitivity, a preregistered 2023 discovery / 2024-2026
validation gate, and (only if that gate passes) a one-position chronological
replay.
"""

from __future__ import annotations

import argparse
import heapq
import json
import math
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[3]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data_feed.okx_trade_bar_loader import OKXTradeBarLoader  # noqa: E402


SCRIPT_VERSION = "1.0.0"
TITLE = "ETH 1m Multi-timeframe Liquidity Sweep, MSS and FVG Limit Study"
TF_MINUTES: tuple[tuple[str, int], ...] = (("15m", 15), ("30m", 30), ("1h", 60), ("4h", 240))
ROUND_TRIP_COSTS = (0.0011, 0.0015, 0.0020)
PRIMARY_EXPIRY_MINUTES = 60
PRIMARY_TARGET_R = 1.5
PRIMARY_HOLD_MINUTES = 360
MAX_MSS_DELAY_MINUTES = 60
ORDER_EXPIRIES = (30, 60, 180)
TARGET_RS = (1.0, 1.5, 2.0)
# Second-pass hypothesis generated by the broad negative result.  It is not a
# replacement for the broad gate: the 4h level is the deepest requested
# liquidity frame, and 75bp is five times the 15bp round-trip cost, capping the
# fee deduction at 0.20R.  The 1R target is deliberately fixed for this second
# experiment rather than selected from its target sensitivity table.
CONDITIONAL_VARIANT = "V1_balanced"
CONDITIONAL_TIMEFRAME = "4h"
CONDITIONAL_MIN_RISK = 0.0075
CONDITIONAL_EXPIRY_MINUTES = 60
CONDITIONAL_TARGET_R = 1.0


@dataclass(frozen=True)
class Variant:
    """Frozen family of definitions; no outcome-informed parameter selection."""

    name: str
    macro_width: int
    micro_width: int
    displacement_atr: float


VARIANTS: tuple[Variant, ...] = (
    Variant("V1_balanced", macro_width=2, micro_width=3, displacement_atr=1.25),
    Variant("V2_clearer_macro", macro_width=3, micro_width=3, displacement_atr=1.25),
    Variant("V3_clearer_micro", macro_width=2, micro_width=5, displacement_atr=1.50),
    Variant("V4_strict", macro_width=3, micro_width=5, displacement_atr=1.50),
)


def _end_exclusive(value: str) -> pd.Timestamp:
    ts = pd.Timestamp(value)
    return ts + pd.Timedelta(days=1) if len(str(value).strip()) <= 10 else ts + pd.Timedelta(microseconds=1)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=TITLE, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--symbol", default="ETH-USDT-SWAP")
    parser.add_argument("--warmup-start-date", default="2022-01-01")
    parser.add_argument("--start-date", default="2023-01-01")
    parser.add_argument("--end-date", default="2026-12-31 23:59:00")
    parser.add_argument("--data-dir", default=None)
    parser.add_argument("--db-name", default="okx_trade_bars.db")
    parser.add_argument("--build-missing", action="store_true", help="Allow the existing data_feed loader to build missing local cache days.")
    parser.add_argument("--out-dir", default="research/ict/mss/results")
    parser.add_argument("--skip-charts", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args(argv)


def load_bars(args: argparse.Namespace) -> pd.DataFrame:
    """Use the project data_feed interface; never query SQLite directly here."""
    print(f"[load] {args.symbol} 1m {args.warmup_start_date} -> {args.end_date}", flush=True)
    loader = OKXTradeBarLoader(symbol=args.symbol, timeframe="1m", data_dir=args.data_dir, db_name=args.db_name)
    frame = loader.fetch_data_by_date_range(
        args.warmup_start_date,
        args.end_date,
        build_missing=bool(args.build_missing),
    )
    needed = ["open", "high", "low", "close"]
    if frame.empty or any(name not in frame.columns for name in needed):
        raise RuntimeError("data_feed returned no usable 1m OHLC data")
    frame = frame.loc[:, needed].copy()
    frame.index = pd.to_datetime(frame.index, errors="coerce")
    frame = frame.loc[~frame.index.isna()].sort_index()
    frame = frame.loc[~frame.index.duplicated(keep="last")]
    for name in needed:
        frame[name] = pd.to_numeric(frame[name], errors="coerce")
    frame = frame.dropna(subset=needed)
    valid_ohlc = (frame["high"] >= frame[["open", "close", "low"]].max(axis=1)) & (
        frame["low"] <= frame[["open", "close", "high"]].min(axis=1)
    )
    frame = frame.loc[valid_ohlc].copy()
    if frame.empty:
        raise RuntimeError("all data_feed rows failed OHLC validation")
    print(f"[load] rows={len(frame):,} actual={frame.index.min()} -> {frame.index.max()}", flush=True)
    return frame


def pivot_mask(values: pd.Series, width: int, *, high: bool) -> np.ndarray:
    """Symmetric local extrema. Future right bars only determine later availability."""
    if width < 1:
        raise ValueError("pivot width must be positive")
    current = values.astype(float)
    mask = current.notna()
    for shift in range(1, width + 1):
        left = current.shift(shift)
        right = current.shift(-shift)
        # Tie breaking assigns a flat plateau to its earliest member.  The rule
        # itself is deterministic and is never used until the right window closes.
        if high:
            mask &= current >= left
            mask &= current > right
        else:
            mask &= current <= left
            mask &= current < right
    return mask.fillna(False).to_numpy(dtype=bool)


def resample_timeframe(bars: pd.DataFrame, minutes: int) -> pd.DataFrame:
    rule = f"{int(minutes)}min"
    grouped = bars.resample(rule, label="left", closed="left")
    out = grouped.agg({"open": "first", "high": "max", "low": "min", "close": "last"})
    counts = grouped["close"].count()
    # Incomplete groups around a source-data gap cannot be macro pivots.
    out.loc[counts.ne(minutes), ["open", "high", "low", "close"]] = np.nan
    return out


def build_macro_levels(bars: pd.DataFrame, width: int) -> pd.DataFrame:
    """Build causal higher-timeframe swing levels from the 1m stream."""
    rows: list[dict[str, object]] = []
    primary_index = bars.index
    for tf_name, minutes in TF_MINUTES:
        higher = resample_timeframe(bars, minutes)
        for side, column, is_high in ((1, "low", False), (-1, "high", True)):
            positions = np.flatnonzero(pivot_mask(higher[column], width, high=is_high))
            for pivot_pos in positions:
                pivot_time = higher.index[pivot_pos]
                # The pivot bar plus all right-side bars must be complete before
                # this level can be observed.  A 1m decision at that timestamp
                # occurs after the information became available at its open.
                available_time = pivot_time + pd.Timedelta(minutes=minutes * (width + 1))
                available_pos = int(primary_index.searchsorted(available_time, side="left"))
                if available_pos >= len(primary_index):
                    continue
                rows.append(
                    {
                        "side": side,
                        "level_type": "swing_low" if side == 1 else "swing_high",
                        "timeframe": tf_name,
                        "timeframe_minutes": minutes,
                        "macro_width": width,
                        "pivot_time": pivot_time,
                        "available_time": available_time,
                        "available_pos": available_pos,
                        "price": float(higher.iloc[pivot_pos][column]),
                    }
                )
    if not rows:
        return pd.DataFrame()
    out = pd.DataFrame(rows).sort_values(
        ["available_pos", "timeframe_minutes", "pivot_time", "side"], kind="mergesort"
    ).reset_index(drop=True)
    out.insert(0, "level_id", np.arange(len(out), dtype=np.int64))
    if not (out["available_time"] > out["pivot_time"]).all():
        raise RuntimeError("macro pivot availability invariant failed")
    return out


def micro_confirmations(bars: pd.DataFrame, width: int) -> tuple[dict[int, list[tuple[float, int]]], dict[int, list[tuple[float, int]]]]:
    """Return pivot confirmations keyed by the bar whose close proves them."""
    high_pos = np.flatnonzero(pivot_mask(bars["high"], width, high=True))
    low_pos = np.flatnonzero(pivot_mask(bars["low"], width, high=False))
    high_map: dict[int, list[tuple[float, int]]] = {}
    low_map: dict[int, list[tuple[float, int]]] = {}
    high_values = bars["high"].to_numpy(dtype=float)
    low_values = bars["low"].to_numpy(dtype=float)
    for pivot_pos in high_pos:
        confirmation_pos = int(pivot_pos + width)
        if confirmation_pos < len(bars):
            high_map.setdefault(confirmation_pos, []).append((float(high_values[pivot_pos]), int(pivot_pos)))
    for pivot_pos in low_pos:
        confirmation_pos = int(pivot_pos + width)
        if confirmation_pos < len(bars):
            low_map.setdefault(confirmation_pos, []).append((float(low_values[pivot_pos]), int(pivot_pos)))
    return high_map, low_map


def prior_atr(bars: pd.DataFrame, length: int = 14) -> np.ndarray:
    high = bars["high"].to_numpy(dtype=float)
    low = bars["low"].to_numpy(dtype=float)
    close = bars["close"].to_numpy(dtype=float)
    previous = np.r_[np.nan, close[:-1]]
    tr = np.maximum(high - low, np.maximum(np.abs(high - previous), np.abs(low - previous)))
    return pd.Series(tr, index=bars.index).shift(1).rolling(length, min_periods=length).mean().to_numpy(dtype=float)


def activation_schedule(levels: pd.DataFrame) -> dict[int, list[dict[str, object]]]:
    schedule: dict[int, list[dict[str, object]]] = {}
    for row in levels.to_dict("records"):
        schedule.setdefault(int(row["available_pos"]), []).append(row)
    return schedule


def _pending_record(side: int, pos: int, timestamp: pd.Timestamp, crossed: list[dict[str, object]], low: float, high: float, serial: int) -> dict[str, object]:
    levels = sorted(crossed, key=lambda item: int(item["timeframe_minutes"]), reverse=True)
    primary = levels[0]
    return {
        "sweep_id": f"{side:+d}_{pos}_{serial}",
        "side": side,
        "sweep_pos": pos,
        "sweep_time": timestamp,
        "stop": float(low if side == 1 else high),
        "macro_level_price": float(primary["price"]),
        "macro_timeframe": str(primary["timeframe"]),
        "macro_timeframe_minutes": int(primary["timeframe_minutes"]),
        "macro_available_time": max(pd.Timestamp(item["available_time"]) for item in levels),
        "macro_levels_swept": len(levels),
    }


def scan_candidates(
    bars: pd.DataFrame,
    levels: pd.DataFrame,
    variant: Variant,
    *,
    research_start: pd.Timestamp,
    research_end_exclusive: pd.Timestamp,
) -> pd.DataFrame:
    """Scan one fully specified strategy family without using future decisions."""
    if levels.empty:
        return pd.DataFrame()
    schedule = activation_schedule(levels)
    high_confirms, low_confirms = micro_confirmations(bars, variant.micro_width)
    atr = prior_atr(bars)
    index = bars.index
    open_ = bars["open"].to_numpy(dtype=float)
    high = bars["high"].to_numpy(dtype=float)
    low = bars["low"].to_numpy(dtype=float)
    close = bars["close"].to_numpy(dtype=float)

    active_lows: list[tuple[float, int, dict[str, object]]] = []  # max-heap by price via -price
    active_highs: list[tuple[float, int, dict[str, object]]] = []  # min-heap by price
    pending: dict[int, dict[str, object] | None] = {1: None, -1: None}
    fvg_wait: dict[int, dict[str, object] | None] = {1: None, -1: None}
    last_highs: list[tuple[float, int]] = []
    last_lows: list[tuple[float, int]] = []
    rows: list[dict[str, object]] = []
    serial = 0

    for pos, timestamp in enumerate(index):
        # Add macro levels known before this 1m candle trades.
        for level in schedule.get(pos, []):
            item = (float(level["price"]), int(level["level_id"]), level)
            if int(level["side"]) == 1:
                heapq.heappush(active_lows, (-item[0], item[1], item[2]))
            else:
                heapq.heappush(active_highs, item)

        crossed_lows: list[dict[str, object]] = []
        crossed_highs: list[dict[str, object]] = []
        while active_lows and -active_lows[0][0] > low[pos]:
            crossed_lows.append(heapq.heappop(active_lows)[2])
        while active_highs and active_highs[0][0] < high[pos]:
            crossed_highs.append(heapq.heappop(active_highs)[2])

        # A one-minute bar that crosses both sides is path-ambiguous.  Consume
        # the levels but do not call it a directional liquidity-sweep setup.
        ambiguous = bool(crossed_lows and crossed_highs)
        if ambiguous:
            pending[1] = None
            pending[-1] = None
            fvg_wait[1] = None
            fvg_wait[-1] = None
        else:
            if crossed_lows:
                serial += 1
                pending[1] = _pending_record(1, pos, timestamp, crossed_lows, low[pos], high[pos], serial)
                pending[-1] = None
                fvg_wait[-1] = None
            elif crossed_highs:
                serial += 1
                pending[-1] = _pending_record(-1, pos, timestamp, crossed_highs, low[pos], high[pos], serial)
                pending[1] = None
                fvg_wait[1] = None

            # The structural stop evolves only until the FVG is confirmed.
            if pending[1] is not None:
                pending[1]["stop"] = min(float(pending[1]["stop"]), float(low[pos]))
            if pending[-1] is not None:
                pending[-1]["stop"] = max(float(pending[-1]["stop"]), float(high[pos]))

        for side in (1, -1):
            current = pending[side]
            if current is not None and pos - int(current["sweep_pos"]) > MAX_MSS_DELAY_MINUTES:
                pending[side] = None
                current = None

            wait = fvg_wait[side]
            if wait is not None and int(wait["mss_pos"]) + 1 == pos:
                # Invalidate a just-detected MSS if another sweep reset its
                # exact premise before the confirming FVG candle closed.
                valid_parent = current is not None and current["sweep_id"] == wait["sweep_id"]
                if valid_parent and pos >= 2:
                    if side == 1:
                        fvg_exists = low[pos] > high[pos - 2]
                        entry_limit = float(low[pos])
                        fvg_size = float(low[pos] - high[pos - 2])
                    else:
                        fvg_exists = high[pos] < low[pos - 2]
                        entry_limit = float(high[pos])
                        fvg_size = float(low[pos - 2] - high[pos])
                    stop = float(current["stop"])
                    valid_risk = entry_limit > stop if side == 1 else entry_limit < stop
                    order_start_pos = pos + 1
                    if fvg_exists and valid_risk and order_start_pos < len(index):
                        order_start_time = index[order_start_pos]
                        if research_start <= order_start_time < research_end_exclusive:
                            risk_fraction = abs(entry_limit - stop) / entry_limit
                            rows.append(
                                {
                                    "candidate_id": f"{variant.name}_{len(rows):06d}",
                                    "variant": variant.name,
                                    "macro_width": variant.macro_width,
                                    "micro_width": variant.micro_width,
                                    "displacement_atr_threshold": variant.displacement_atr,
                                    "side": side,
                                    "side_name": "LONG" if side == 1 else "SHORT",
                                    "sweep_id": current["sweep_id"],
                                    "sweep_pos": int(current["sweep_pos"]),
                                    "sweep_time": current["sweep_time"],
                                    "macro_level_price": current["macro_level_price"],
                                    "macro_timeframe": current["macro_timeframe"],
                                    "macro_timeframe_minutes": current["macro_timeframe_minutes"],
                                    "macro_available_time": current["macro_available_time"],
                                    "macro_levels_swept": current["macro_levels_swept"],
                                    "mss_pos": int(wait["mss_pos"]),
                                    "mss_time": index[int(wait["mss_pos"])],
                                    "mss_level": wait["mss_level"],
                                    "mss_delay_minutes": int(wait["mss_pos"]) - int(current["sweep_pos"]),
                                    "displacement_atr": wait["displacement_atr"],
                                    "setup_pos": pos,
                                    "setup_time": timestamp,
                                    "fvg_size": fvg_size,
                                    "fvg_size_atr": fvg_size / atr[int(wait["mss_pos"])] if np.isfinite(atr[int(wait["mss_pos"])]) else np.nan,
                                    "entry_limit": entry_limit,
                                    "stop_price": stop,
                                    "risk_fraction": risk_fraction,
                                    "order_start_pos": order_start_pos,
                                    "order_start_time": order_start_time,
                                }
                            )
                        # One completed FVG consumes the sweep premise.  A new
                        # independent macro sweep is required for another order.
                        pending[side] = None
                fvg_wait[side] = None

        # MSS is measured on this closed candle using only pivots that were
        # confirmed by earlier closed candles.  Newly confirmed pivots below are
        # deliberately available from the next loop iteration.
        if pos >= 1 and np.isfinite(atr[pos]):
            body = abs(close[pos] - open_[pos])
            full_range = high[pos] - low[pos]
            body_ratio = body / full_range if full_range > 0 else 0.0
            long_context = (
                (len(last_highs) >= 2 and last_highs[-1][0] < last_highs[-2][0])
                or (len(last_lows) >= 2 and last_lows[-1][0] < last_lows[-2][0])
            )
            short_context = (
                (len(last_highs) >= 2 and last_highs[-1][0] > last_highs[-2][0])
                or (len(last_lows) >= 2 and last_lows[-1][0] > last_lows[-2][0])
            )
            displacement_ok = body >= variant.displacement_atr * atr[pos] and body_ratio >= 0.55
            long_pending = pending[1]
            short_pending = pending[-1]
            if (
                long_pending is not None
                and len(last_highs) >= 1
                and pos - int(long_pending["sweep_pos"]) <= MAX_MSS_DELAY_MINUTES
                and long_context
                and close[pos - 1] <= last_highs[-1][0] < close[pos]
                and displacement_ok
                and close[pos] >= low[pos] + 0.65 * full_range
            ):
                fvg_wait[1] = {
                    "sweep_id": long_pending["sweep_id"],
                    "mss_pos": pos,
                    "mss_level": float(last_highs[-1][0]),
                    "displacement_atr": body / atr[pos],
                }
            if (
                short_pending is not None
                and len(last_lows) >= 1
                and pos - int(short_pending["sweep_pos"]) <= MAX_MSS_DELAY_MINUTES
                and short_context
                and close[pos - 1] >= last_lows[-1][0] > close[pos]
                and displacement_ok
                and close[pos] <= high[pos] - 0.65 * full_range
            ):
                fvg_wait[-1] = {
                    "sweep_id": short_pending["sweep_id"],
                    "mss_pos": pos,
                    "mss_level": float(last_lows[-1][0]),
                    "displacement_atr": body / atr[pos],
                }

        for value, pivot_pos in high_confirms.get(pos, []):
            last_highs.append((value, pivot_pos))
            last_highs = last_highs[-2:]
        for value, pivot_pos in low_confirms.get(pos, []):
            last_lows.append((value, pivot_pos))
            last_lows = last_lows[-2:]

    out = pd.DataFrame(rows)
    if out.empty:
        return out
    out["year"] = pd.to_datetime(out["order_start_time"]).dt.year.astype(int)
    causal_checks = {
        "macro_known_before_sweep": pd.to_datetime(out["macro_available_time"]) <= pd.to_datetime(out["sweep_time"]),
        "mss_after_sweep": out["mss_pos"] >= out["sweep_pos"],
        "fvg_after_mss": out["setup_pos"] == out["mss_pos"] + 1,
        "order_after_fvg": out["order_start_pos"] == out["setup_pos"] + 1,
        "positive_risk": out["risk_fraction"] > 0,
    }
    for name, check in causal_checks.items():
        out[name] = check.to_numpy(dtype=bool) if isinstance(check, pd.Series) else bool(check)
        if not bool(np.all(check)):
            raise RuntimeError(f"causal invariant failed: {name}")
    return out


def attach_first_fills(candidates: pd.DataFrame, bars: pd.DataFrame, max_expiry: int) -> pd.DataFrame:
    out = candidates.copy()
    if out.empty:
        return out
    high = bars["high"].to_numpy(dtype=float)
    low = bars["low"].to_numpy(dtype=float)
    open_ = bars["open"].to_numpy(dtype=float)
    index = bars.index
    fill_pos = np.full(len(out), -1, dtype=np.int64)
    fill_price = np.full(len(out), np.nan, dtype=float)
    for row_idx, row in enumerate(out.itertuples(index=False)):
        start = int(row.order_start_pos)
        end = min(start + int(max_expiry) - 1, len(index) - 1)
        limit = float(row.entry_limit)
        side = int(row.side)
        for pos in range(start, end + 1):
            hit = low[pos] <= limit if side == 1 else high[pos] >= limit
            if hit:
                fill_pos[row_idx] = pos
                # A resting buy/sell limit benefits from a favorable open gap.
                fill_price[row_idx] = min(open_[pos], limit) if side == 1 else max(open_[pos], limit)
                break
    out["first_fill_pos"] = fill_pos
    out["first_fill_time"] = pd.NaT
    has_fill = fill_pos >= 0
    if has_fill.any():
        out.loc[has_fill, "first_fill_time"] = index[fill_pos[has_fill]]
    out["first_fill_price"] = fill_price
    out["first_fill_age_minutes"] = np.where(has_fill, fill_pos - out["order_start_pos"].to_numpy(dtype=np.int64) + 1, np.nan)
    out["first_fill_status"] = np.where(has_fill, "FILLED", "EXPIRED")
    return out


def replay_outcomes(
    fills: pd.DataFrame,
    bars: pd.DataFrame,
    *,
    expiries: Iterable[int] = ORDER_EXPIRIES,
    targets: Iterable[float] = TARGET_RS,
    hold_minutes: int = PRIMARY_HOLD_MINUTES,
) -> pd.DataFrame:
    """Conservative OHLC stop/target replay for every predeclared sensitivity."""
    if fills.empty:
        return pd.DataFrame()
    high = bars["high"].to_numpy(dtype=float)
    low = bars["low"].to_numpy(dtype=float)
    close = bars["close"].to_numpy(dtype=float)
    index = bars.index
    rows: list[dict[str, object]] = []
    targets = tuple(float(value) for value in targets)
    for row in fills.itertuples(index=False):
        if int(row.first_fill_pos) < 0:
            continue
        fill_age = int(row.first_fill_age_minutes)
        fill_pos = int(row.first_fill_pos)
        side = int(row.side)
        entry = float(row.first_fill_price)
        stop = float(row.stop_price)
        risk = abs(entry - stop) / entry
        for expiry in expiries:
            if fill_age > int(expiry):
                continue
            for target_r in targets:
                gap_invalid = entry <= stop if side == 1 else entry >= stop
                target = entry * (1.0 + side * risk * target_r)
                exit_pos = fill_pos
                exit_price = entry
                outcome = "GAP_INVALID" if gap_invalid else "TIME"
                if gap_invalid:
                    gross_r = -1.0
                else:
                    horizon_end = min(fill_pos + int(hold_minutes) - 1, len(index) - 1)
                    for pos in range(fill_pos, horizon_end + 1):
                        stop_hit = low[pos] <= stop if side == 1 else high[pos] >= stop
                        target_hit = high[pos] >= target if side == 1 else low[pos] <= target
                        # OHLC cannot reveal intra-bar order; stop first prevents
                        # optimistic outcomes when both boundaries print.
                        if stop_hit:
                            exit_pos, exit_price, outcome = pos, stop, "SL"
                            break
                        if target_hit:
                            exit_pos, exit_price, outcome = pos, target, "TP"
                            break
                    else:
                        exit_pos, exit_price, outcome = horizon_end, close[horizon_end], "TIME"
                    gross_r = side * (exit_price / entry - 1.0) / risk
                record = {
                    "candidate_id": row.candidate_id,
                    "variant": row.variant,
                    "year": int(row.year),
                    "side": side,
                    "side_name": row.side_name,
                    "expiry_minutes": int(expiry),
                    "target_r": float(target_r),
                    "fill_pos": fill_pos,
                    "fill_time": index[fill_pos],
                    "fill_age_minutes": fill_age,
                    "entry_price": entry,
                    "stop_price": stop,
                    "risk_fraction": risk,
                    "target_price": target,
                    "exit_pos": exit_pos,
                    "exit_time": index[exit_pos],
                    "exit_price": exit_price,
                    "outcome": outcome,
                    "gross_r": gross_r,
                    "gross_return_fraction": gross_r * risk,
                }
                for cost in ROUND_TRIP_COSTS:
                    tag = f"net_r_{int(round(cost * 10000)):02d}bp"
                    record[tag] = gross_r - cost / risk
                rows.append(record)
    return pd.DataFrame(rows)


def _outcome_stats(frame: pd.DataFrame) -> dict[str, float | int]:
    if frame.empty:
        return {
            "n_filled": 0,
            "win_rate_15bp": np.nan,
            "avg_gross_r": np.nan,
            "median_gross_r": np.nan,
            "avg_net_r_11bp": np.nan,
            "avg_net_r_15bp": np.nan,
            "avg_net_r_20bp": np.nan,
            "profit_factor_15bp": np.nan,
            "t_stat_15bp": np.nan,
        }
    net = frame["net_r_15bp"].to_numpy(dtype=float)
    positive = net[net > 0].sum()
    negative = net[net < 0].sum()
    std = float(np.std(net, ddof=1)) if len(net) > 1 else np.nan
    return {
        "n_filled": int(len(frame)),
        "win_rate_15bp": float(np.mean(net > 0)),
        "avg_gross_r": float(frame["gross_r"].mean()),
        "median_gross_r": float(frame["gross_r"].median()),
        "avg_net_r_11bp": float(frame["net_r_11bp"].mean()),
        "avg_net_r_15bp": float(frame["net_r_15bp"].mean()),
        "avg_net_r_20bp": float(frame["net_r_20bp"].mean()),
        "profit_factor_15bp": float(positive / abs(negative)) if negative < 0 else np.inf,
        "t_stat_15bp": float(np.mean(net) / std * math.sqrt(len(net))) if np.isfinite(std) and std > 0 else np.nan,
    }


def build_scorecard(candidates: pd.DataFrame, fills: pd.DataFrame, outcomes: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    if candidates.empty:
        return pd.DataFrame()
    for variant in sorted(candidates["variant"].unique()):
        candidate_variant = candidates.loc[candidates["variant"].eq(variant)]
        for expiry in ORDER_EXPIRIES:
            eligible = fills.loc[
                fills["variant"].eq(variant)
                & fills["first_fill_pos"].ge(0)
                & fills["first_fill_age_minutes"].le(expiry)
            ]
            for target in TARGET_RS:
                outcome_subset = outcomes.loc[
                    outcomes["variant"].eq(variant)
                    & outcomes["expiry_minutes"].eq(expiry)
                    & outcomes["target_r"].eq(float(target))
                ]
                for year in (2023, 2024, 2025, 2026, "ALL"):
                    if year == "ALL":
                        cand_year = candidate_variant
                        fill_year = eligible
                        outcome_year = outcome_subset
                    else:
                        cand_year = candidate_variant.loc[candidate_variant["year"].eq(year)]
                        fill_year = eligible.loc[eligible["year"].eq(year)]
                        outcome_year = outcome_subset.loc[outcome_subset["year"].eq(year)]
                    stats = _outcome_stats(outcome_year)
                    placed = int(len(cand_year))
                    row: dict[str, object] = {
                        "variant": variant,
                        "expiry_minutes": expiry,
                        "target_r": target,
                        "year": year,
                        "n_placed": placed,
                        "n_filled": stats.pop("n_filled"),
                        "fill_rate": float(len(fill_year) / placed) if placed else np.nan,
                    }
                    row.update(stats)
                    rows.append(row)
    return pd.DataFrame(rows)


def select_edge(scorecard: pd.DataFrame) -> tuple[pd.DataFrame, str | None, bool]:
    """Predeclared 2023 selection and 2024-2026 validation gate."""
    if scorecard.empty:
        return pd.DataFrame(), None, False
    primary = scorecard.loc[
        scorecard["expiry_minutes"].eq(PRIMARY_EXPIRY_MINUTES)
        & scorecard["target_r"].eq(PRIMARY_TARGET_R)
    ].copy()
    discovery = primary.loc[primary["year"].eq(2023) & primary["n_filled"].ge(25)].copy()
    if discovery.empty:
        return pd.DataFrame(
            [{"gate": "discovery_sample", "passed": False, "detail": "No frozen variant had >=25 filled 2023 trades."}]
        ), None, False
    selected = str(discovery.sort_values(["avg_net_r_15bp", "n_filled"], ascending=[False, False]).iloc[0]["variant"])
    annual = primary.loc[primary["variant"].eq(selected) & primary["year"].isin([2023, 2024, 2025, 2026])].copy()
    pooled_oos = _outcome_stats(
        pd.DataFrame()
    )
    # Scorecard contains averages, but pooled mean must be weighted by trades.
    oos = annual.loc[annual["year"].isin([2024, 2025, 2026])]
    oos_n = int(oos["n_filled"].sum())
    oos_mean = float(np.average(oos["avg_net_r_15bp"], weights=oos["n_filled"])) if oos_n and oos["avg_net_r_15bp"].notna().all() else np.nan
    sensitivity = scorecard.loc[
        scorecard["variant"].eq(selected) & scorecard["year"].eq("ALL")
    ]
    # Sensitivity is deliberately evaluated on the validation years only below.
    validation_positive_years = int(
        annual.loc[annual["year"].isin([2024, 2025]), "avg_net_r_15bp"].gt(0).sum()
    )
    y2026_ok = bool(
        annual.loc[annual["year"].eq(2026), "avg_net_r_15bp"].iloc[0] > -0.10
    ) if annual["year"].eq(2026).any() else False
    gates = [
        ("2023 discovery", bool(annual.loc[annual["year"].eq(2023), "avg_net_r_15bp"].iloc[0] > 0), "positive average net R after 15bp costs; >=25 fills"),
        ("OOS sample", oos_n >= 75, f"2024-2026 filled trades={oos_n}"),
        ("OOS pooled expectancy", bool(np.isfinite(oos_mean) and oos_mean > 0), f"weighted net R={oos_mean:.3f}" if np.isfinite(oos_mean) else "unavailable"),
        ("Full-year stability", validation_positive_years == 2, f"positive among 2024 and 2025={validation_positive_years}/2"),
        ("2026 YTD guardrail", y2026_ok, "not worse than -0.10R after 15bp costs"),
    ]
    gate_frame = pd.DataFrame(
        [{"selected_variant": selected, "gate": name, "passed": passed, "detail": detail} for name, passed, detail in gates]
    )
    return gate_frame, selected, bool(gate_frame["passed"].all())


def conditional_edge_study(
    candidates: pd.DataFrame,
    fills: pd.DataFrame,
    outcomes: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, bool]:
    """Test the economically feasible 4h conditional hypothesis.

    The broad pattern is deliberately left intact above.  This second pass asks
    a narrower question: when the sweep is on the deepest requested timeframe
    and the structural stop is sufficiently wide to make a 15bp round trip no
    more than 0.20R, is the one-R FVG retrace still positive in later years?
    """
    selected = candidates.loc[
        candidates["variant"].eq(CONDITIONAL_VARIANT)
        & candidates["macro_timeframe"].eq(CONDITIONAL_TIMEFRAME)
        & candidates["risk_fraction"].ge(CONDITIONAL_MIN_RISK)
    ].copy()
    if selected.empty:
        return selected, pd.DataFrame(), pd.DataFrame(), pd.DataFrame(), False
    eligible_fills = fills.loc[
        fills["candidate_id"].isin(selected["candidate_id"])
        & fills["first_fill_pos"].ge(0)
        & fills["first_fill_age_minutes"].le(CONDITIONAL_EXPIRY_MINUTES)
    ].copy()
    primary = outcomes.loc[
        outcomes["candidate_id"].isin(selected["candidate_id"])
        & outcomes["expiry_minutes"].eq(CONDITIONAL_EXPIRY_MINUTES)
        & outcomes["target_r"].eq(CONDITIONAL_TARGET_R)
    ].copy()
    annual_rows: list[dict[str, object]] = []
    for year in (2023, 2024, 2025, 2026, "ALL"):
        candidate_year = selected if year == "ALL" else selected.loc[selected["year"].eq(year)]
        fill_year = eligible_fills if year == "ALL" else eligible_fills.loc[eligible_fills["year"].eq(year)]
        trade_year = primary if year == "ALL" else primary.loc[primary["year"].eq(year)]
        stats = _outcome_stats(trade_year)
        n_filled = int(stats.pop("n_filled"))
        annual_rows.append(
            {
                "year": year,
                "n_placed": int(len(candidate_year)),
                "n_filled": n_filled,
                "fill_rate": n_filled / len(candidate_year) if len(candidate_year) else np.nan,
                **stats,
            }
        )
    annual = pd.DataFrame(annual_rows)
    sensitivity_rows: list[dict[str, object]] = []
    for expiry in ORDER_EXPIRIES:
        for target in TARGET_RS:
            subset = outcomes.loc[
                outcomes["candidate_id"].isin(selected["candidate_id"])
                & outcomes["expiry_minutes"].eq(expiry)
                & outcomes["target_r"].eq(float(target))
            ]
            all_stats = _outcome_stats(subset)
            validation_stats = _outcome_stats(subset.loc[subset["year"].isin([2025, 2026])])
            sensitivity_rows.append(
                {
                    "expiry_minutes": expiry,
                    "target_r": target,
                    "all_n_filled": all_stats["n_filled"],
                    "all_avg_net_r_11bp": all_stats["avg_net_r_11bp"],
                    "all_avg_net_r_15bp": all_stats["avg_net_r_15bp"],
                    "all_avg_net_r_20bp": all_stats["avg_net_r_20bp"],
                    "validation_2025_26_n_filled": validation_stats["n_filled"],
                    "validation_2025_26_net_r_15bp": validation_stats["avg_net_r_15bp"],
                    "validation_2025_26_net_r_20bp": validation_stats["avg_net_r_20bp"],
                }
            )
    sensitivity = pd.DataFrame(sensitivity_rows)
    y2025_26 = primary.loc[primary["year"].isin([2025, 2026])]
    y2025_26_stats = _outcome_stats(y2025_26)
    annual_indexed = annual.set_index("year")
    annual_20bp_positive = bool(
        annual_indexed.loc[[2023, 2024, 2025, 2026], "avg_net_r_20bp"].gt(0).all()
    )
    one_r_sensitivity = sensitivity.loc[sensitivity["target_r"].eq(1.0)]
    gates = [
        ("Sample by calendar year", bool(annual_indexed.loc[[2023, 2024, 2025, 2026], "n_filled"].ge(25).all()), "at least 25 filled trades in each observed year"),
        ("2025-2026 validation sample", int(y2025_26_stats["n_filled"]) >= 60, f"filled trades={int(y2025_26_stats['n_filled'])}"),
        ("2025-2026 validation expectancy", bool(y2025_26_stats["avg_net_r_15bp"] > 0), f"15bp net R={y2025_26_stats['avg_net_r_15bp']:.3f}"),
        ("20bp cost stress", annual_20bp_positive, "each calendar year remains positive after 20bp round-trip cost"),
        ("Order-life robustness", bool(one_r_sensitivity["all_avg_net_r_20bp"].gt(0).all()), "1R remains positive at 30/60/180-minute order life after 20bp cost"),
    ]
    gate = pd.DataFrame(
        [
            {
                "definition": "V1 balanced + 4h first sweep + risk >= 75bp + FVG upper/lower edge + 1R",
                "gate": name,
                "passed": passed,
                "detail": detail,
            }
            for name, passed, detail in gates
        ]
    )
    return selected, annual, sensitivity, gate, bool(gate["passed"].all())


def sequential_backtest(
    candidates: pd.DataFrame,
    fills: pd.DataFrame,
    outcomes: pd.DataFrame,
    *,
    expiry_minutes: int,
    target_r: float,
    label: str,
) -> pd.DataFrame:
    """One-position chronological replay for a candidate subset."""
    if candidates.empty:
        return pd.DataFrame()
    candidate_rows = candidates.sort_values(
        ["order_start_pos", "candidate_id"], kind="mergesort"
    )
    fill_cols = fills[["candidate_id", "first_fill_pos", "first_fill_age_minutes"]]
    trade_cols = outcomes.loc[
        outcomes["candidate_id"].isin(candidate_rows["candidate_id"])
        & outcomes["expiry_minutes"].eq(expiry_minutes)
        & outcomes["target_r"].eq(target_r)
    ].copy()
    merged = candidate_rows.merge(fill_cols, on="candidate_id", how="left").merge(
        trade_cols,
        on="candidate_id",
        how="left",
        suffixes=("", "_trade"),
    )
    rows: list[dict[str, object]] = []
    busy_until = -1
    skipped = 0
    for item in merged.itertuples(index=False):
        if int(item.order_start_pos) < busy_until:
            skipped += 1
            continue
        age = getattr(item, "first_fill_age_minutes")
        if pd.isna(age) or float(age) > expiry_minutes or pd.isna(getattr(item, "gross_r")):
            busy_until = int(item.order_start_pos) + expiry_minutes
            continue
        busy_until = int(getattr(item, "exit_pos")) + 1
        rows.append(
            {
                "candidate_id": item.candidate_id,
                "variant": label,
                "order_start_time": item.order_start_time,
                "fill_time": getattr(item, "fill_time"),
                "exit_time": getattr(item, "exit_time"),
                "side_name": item.side_name,
                "outcome": getattr(item, "outcome"),
                "gross_r": getattr(item, "gross_r"),
                "net_r_15bp": getattr(item, "net_r_15bp"),
                "risk_fraction": getattr(item, "risk_fraction"),
            }
        )
    out = pd.DataFrame(rows)
    if out.empty:
        return out
    out["trade_number"] = np.arange(1, len(out) + 1)
    out["equity_r"] = out["net_r_15bp"].cumsum()
    out["equity_peak_r"] = out["equity_r"].cummax()
    out["drawdown_r"] = out["equity_r"] - out["equity_peak_r"]
    out.attrs["skipped_overlapping_candidates"] = skipped
    return out


def coverage_table(bars: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for year, part in bars.groupby(bars.index.year):
        gaps = part.index.to_series().diff().gt(pd.Timedelta(minutes=1))
        rows.append(
            {
                "year": int(year),
                "bars": int(len(part)),
                "first_bar": part.index.min(),
                "last_bar": part.index.max(),
                "gaps_gt_1m": int(gaps.sum()),
                "largest_gap_minutes": float(part.index.to_series().diff().max().total_seconds() / 60.0) if len(part) > 1 else np.nan,
            }
        )
    return pd.DataFrame(rows)


def markdown_table(frame: pd.DataFrame, columns: Sequence[str], n: int | None = None) -> str:
    if frame.empty:
        return "_No rows._"
    data = frame.loc[:, [column for column in columns if column in frame.columns]].copy()
    if n is not None:
        data = data.head(n)
    for column in data.columns:
        if pd.api.types.is_float_dtype(data[column]):
            data[column] = data[column].map(lambda value: "" if pd.isna(value) else f"{value:.3f}")
        else:
            data[column] = data[column].astype(str)
    header = "| " + " | ".join(data.columns) + " |"
    divider = "| " + " | ".join("---" for _ in data.columns) + " |"
    body = ["| " + " | ".join(str(value) for value in row) + " |" for row in data.itertuples(index=False, name=None)]
    return "\n".join([header, divider, *body])


def write_charts(out_dir: Path, scorecard: pd.DataFrame, selected: str | None) -> list[str]:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as exc:  # pragma: no cover - minimal environments
        print(f"[charts] skipped: {exc}", flush=True)
        return []
    chart_files: list[str] = []
    primary = scorecard.loc[
        scorecard["expiry_minutes"].eq(PRIMARY_EXPIRY_MINUTES)
        & scorecard["target_r"].eq(PRIMARY_TARGET_R)
    ].copy()
    if not primary.empty:
        summary = primary.loc[primary["year"].eq("ALL")].sort_values("avg_net_r_15bp")
        fig, ax = plt.subplots(figsize=(8.0, 4.5))
        ax.barh(summary["variant"], summary["avg_net_r_15bp"], color="#2f6b9a")
        ax.axvline(0, color="#29323c", linewidth=1)
        ax.set_title("Primary 60m-limit / 1.5R setup: net expectancy")
        ax.set_xlabel("Average R after 15bp round-trip cost")
        ax.set_ylabel("Frozen definition family")
        fig.tight_layout()
        path = out_dir / "01_primary_variant_expectancy.png"
        fig.savefig(path, dpi=160)
        plt.close(fig)
        chart_files.append(path.name)
    if selected and not primary.empty:
        yearly = primary.loc[primary["variant"].eq(selected) & primary["year"].isin([2023, 2024, 2025, 2026])].copy()
        if not yearly.empty:
            fig, ax1 = plt.subplots(figsize=(8.0, 4.5))
            ax1.bar(yearly["year"].astype(str), yearly["avg_net_r_15bp"], color="#b2762b")
            ax1.axhline(0, color="#29323c", linewidth=1)
            ax1.set_ylabel("Average R after 15bp")
            ax1.set_title(f"{selected}: annual net expectancy and sample size")
            ax2 = ax1.twinx()
            ax2.plot(yearly["year"].astype(str), yearly["n_filled"], marker="o", color="#444444")
            ax2.set_ylabel("Filled trades")
            fig.tight_layout()
            path = out_dir / "02_selected_annual_expectancy.png"
            fig.savefig(path, dpi=160)
            plt.close(fig)
            chart_files.append(path.name)
    return chart_files


def render_report(
    path: Path,
    *,
    bars: pd.DataFrame,
    coverage: pd.DataFrame,
    candidates: pd.DataFrame,
    scorecard: pd.DataFrame,
    gates: pd.DataFrame,
    selected: str | None,
    has_edge: bool,
    backtest: pd.DataFrame,
    conditional_annual: pd.DataFrame,
    conditional_sensitivity: pd.DataFrame,
    conditional_gate: pd.DataFrame,
    conditional_edge: bool,
    conditional_backtest: pd.DataFrame,
    chart_files: Sequence[str],
) -> None:
    primary = scorecard.loc[
        scorecard["expiry_minutes"].eq(PRIMARY_EXPIRY_MINUTES)
        & scorecard["target_r"].eq(PRIMARY_TARGET_R)
    ] if not scorecard.empty else pd.DataFrame()
    selected_annual = primary.loc[primary["variant"].eq(selected) & primary["year"].isin([2023, 2024, 2025, 2026])] if selected else pd.DataFrame()
    status = "EDGE CONFIRMED BY THE BROAD PREDECLARED GATE" if has_edge else "NO BROAD EDGE CONFIRMED BY THE PREDECLARED GATE"
    summary = (
        f"The 2023 discovery winner is **{selected}**.  "
        f"The validation gate is **{'passed' if has_edge else 'not passed'}** after 15bp round-trip cost and conservative same-bar handling."
        if selected else "No variant reached the minimum 2023 filled-trade count, so no selection or validation claim is made."
    )
    lines = [
        f"# {TITLE}",
        "",
        "## Technical summary",
        "",
        f"**Result: {status}.** {summary}",
        "",
        "The broad unfiltered MSS/FVG pattern fails. A second, explicitly labeled conditional hypothesis is reported below: it is promising but narrower and has less structural-definition robustness, so it is not a deployment claim.",
        "",
        "## Key findings with visual evidence",
        "",
        "The primary specification holds a 60-minute FVG limit order, targets 1.5R, exits remaining positions after six hours, and deducts 15bp round-trip cost. Variants were frozen before outcomes were inspected; the winner is selected only from 2023, then checked in 2024-2026.",
        "",
        markdown_table(selected_annual, ["year", "n_placed", "n_filled", "fill_rate", "win_rate_15bp", "avg_net_r_15bp", "profit_factor_15bp", "t_stat_15bp"]),
        "",
    ]
    for file_name in chart_files:
        lines.extend([f"![{file_name}](results/{file_name})", ""])
    lines.extend(
        [
            "## Scope, data, and metric definitions",
            "",
            f"Only `open`, `high`, `low`, and `close` from `src.data_feed.OKXTradeBarLoader` were used. The query requested 2022-01-01 through 2026-12-31; cached coverage ended at **{bars.index.max():%Y-%m-%d %H:%M}**. 2022 is warm-up only; orders activated from 2023 onward are measured.",
            "",
            markdown_table(coverage, ["year", "bars", "first_bar", "last_bar", "gaps_gt_1m", "largest_gap_minutes"]),
            "",
            "A macro liquidity level is a 15m, 30m, 1h, or 4h swing extreme, resampled strictly from the same 1m series. The strategy only sees it after the right-side swing window completes. A low/high is consumed on its first strict cross; simultaneous high-and-low sweeps are excluded as path-ambiguous.",
            "",
            "## Methodology",
            "",
            "1. Scan the causal first sweep of active macro swing levels.",
            "2. Within 60 minutes, require a countertrend 1m structure break of a previously confirmed micro swing plus a displacement candle (body/previous 14-bar ATR and body/range filters).",
            "3. On the next candle, require a three-candle FVG. Enter at that candle's low for a long or high for a short, with eligibility delayed one more 1m bar.",
            "4. Stop at the running sweep extreme through FVG confirmation. Model first touch of the resting limit; for a candle touching both stop and target, record the stop first.",
            "5. Report 30/60/180-minute order-life and 1/1.5/2R target sensitivity. Cost columns use 11bp, 15bp, and 20bp round-trip deductions.",
            "",
            f"Candidate count across the four frozen structural variants: **{len(candidates):,}**. The full event audit is `02_candidate_events.csv.gz`; individual replay results are `04_trade_replay.csv.gz`.",
            "",
            "## Conditional 4h candidate",
            "",
            "The broad failure motivated a second economic-feasibility hypothesis: retain only the deepest requested macro liquidity frame (4h) and require stop distance of at least 75bp, which is five times the 15bp cost and therefore caps fee drag at 0.20R. Its exit is fixed at 1R with a 60-minute limit life and six-hour time stop. This hypothesis is **post-broad-study**; 2025-2026 are the cleanest later-period check, not a claim of fully preregistered discovery.",
            "",
            f"**Conditional result: {'candidate edge passed its stated checks' if conditional_edge else 'candidate edge did not pass its stated checks'}.**",
            "",
            markdown_table(conditional_annual, ["year", "n_placed", "n_filled", "fill_rate", "win_rate_15bp", "avg_net_r_11bp", "avg_net_r_15bp", "avg_net_r_20bp", "profit_factor_15bp", "t_stat_15bp"]),
            "",
            "The order-life/target sensitivity below is included to show whether a 1R result is a single fill-timing artifact. It does not make the target an optimized selection rule.",
            "",
            markdown_table(conditional_sensitivity, ["expiry_minutes", "target_r", "all_n_filled", "all_avg_net_r_15bp", "all_avg_net_r_20bp", "validation_2025_26_n_filled", "validation_2025_26_net_r_15bp", "validation_2025_26_net_r_20bp"]),
            "",
            "## Limitations, uncertainty, and robustness checks",
            "",
            markdown_table(gates, ["selected_variant", "gate", "passed", "detail"]),
            "",
            markdown_table(conditional_gate, ["definition", "gate", "passed", "detail"]),
            "",
            "The data are 1m OHLC, so intra-candle order is not observable; same-bar ambiguity is conservatively adverse. The model does not include spread, queue priority, adverse selection, partial fills, funding, liquidation, or exchange outages. Minute gaps remain visible in the coverage table and no higher-timeframe bar spanning a gap is used as a swing pivot. The conditional candidate is sensitive to the macro/micro swing definition: V1 is positive while the stricter V2-V4 families are not. Parameter sensitivity is descriptive, not a license to select an in-sample optimum.",
            "",
            "## Recommended next steps",
            "",
            "Do not trade the broad unfiltered MSS/FVG pattern. For the conditional candidate, freeze the 4h/75bp/1R definition and run a queue-aware, no-parameter-change paper test; use a new untouched period before treating its small historical expectancy as tradable.",
            "",
            "## Further questions",
            "",
            "Does an executable FVG fill differ materially from the OHLC first-touch assumption? Do macro swing quality, session, or volatility regime improve the result out of sample rather than merely re-ranking in-sample variants? These questions require a new frozen experiment rather than changing this study's gate.",
        ]
    )
    if has_edge and not backtest.empty:
        max_dd = float(backtest["drawdown_r"].min())
        lines.extend(
            [
                "",
                "## Conditional one-position backtest",
                "",
                f"The validation-selected variant was replayed chronologically with one active order/position at a time. It produced **{len(backtest):,}** filled trades, final **{backtest['equity_r'].iloc[-1]:.2f}R**, and maximum drawdown **{max_dd:.2f}R** after 15bp costs. The chronological ledger is `07_single_position_backtest.csv`.",
            ]
        )
    if conditional_edge and not conditional_backtest.empty:
        max_dd = float(conditional_backtest["drawdown_r"].min())
        lines.extend(
            [
                "",
                "## Conditional one-position backtest",
                "",
                f"The conditional candidate was replayed chronologically with one active order/position at a time. It produced **{len(conditional_backtest):,}** filled trades, final **{conditional_backtest['equity_r'].iloc[-1]:.2f}R**, and maximum drawdown **{max_dd:.2f}R** after 15bp costs. The chronological ledger is `12_conditional_single_position_backtest.csv`.",
            ]
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_outputs(
    out_dir: Path,
    *,
    args: argparse.Namespace,
    bars: pd.DataFrame,
    levels_by_width: dict[int, pd.DataFrame],
    candidates: pd.DataFrame,
    fills: pd.DataFrame,
    outcomes: pd.DataFrame,
    scorecard: pd.DataFrame,
    gates: pd.DataFrame,
    selected: str | None,
    has_edge: bool,
    backtest: pd.DataFrame,
    conditional_annual: pd.DataFrame,
    conditional_sensitivity: pd.DataFrame,
    conditional_gate: pd.DataFrame,
    conditional_edge: bool,
    conditional_backtest: pd.DataFrame,
) -> list[str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    coverage = coverage_table(bars)
    coverage.to_csv(out_dir / "01_data_coverage.csv", index=False, encoding="utf-8-sig")
    candidates.to_csv(out_dir / "02_candidate_events.csv.gz", index=False, compression="gzip")
    fills.to_csv(out_dir / "03_limit_fill_audit.csv.gz", index=False, compression="gzip")
    outcomes.to_csv(out_dir / "04_trade_replay.csv.gz", index=False, compression="gzip")
    scorecard.to_csv(out_dir / "05_scorecard.csv", index=False, encoding="utf-8-sig")
    gates.to_csv(out_dir / "06_edge_gate.csv", index=False, encoding="utf-8-sig")
    if has_edge and not backtest.empty:
        backtest.to_csv(out_dir / "07_single_position_backtest.csv", index=False, encoding="utf-8-sig")
    levels = pd.concat(levels_by_width.values(), ignore_index=True) if levels_by_width else pd.DataFrame()
    levels.to_csv(out_dir / "08_macro_level_audit.csv.gz", index=False, compression="gzip")
    conditional_annual.to_csv(out_dir / "09_conditional_edge_annual.csv", index=False, encoding="utf-8-sig")
    conditional_sensitivity.to_csv(out_dir / "10_conditional_edge_sensitivity.csv", index=False, encoding="utf-8-sig")
    conditional_gate.to_csv(out_dir / "11_conditional_edge_gate.csv", index=False, encoding="utf-8-sig")
    if conditional_edge and not conditional_backtest.empty:
        conditional_backtest.to_csv(out_dir / "12_conditional_single_position_backtest.csv", index=False, encoding="utf-8-sig")
    manifest = {
        "title": TITLE,
        "script": str(Path(__file__).relative_to(PROJECT_ROOT)),
        "script_version": SCRIPT_VERSION,
        "symbol": args.symbol,
        "data_interface": "src.data_feed.okx_trade_bar_loader.OKXTradeBarLoader.fetch_data_by_date_range",
        "ohlc_only": True,
        "requested_window": [args.warmup_start_date, args.end_date],
        "actual_window": [str(bars.index.min()), str(bars.index.max())],
        "research_window": [args.start_date, str(bars.index.max())],
        "warmup_window": [args.warmup_start_date, "2022-12-31 23:59:00"],
        "timeframes": TF_MINUTES,
        "variants": [asdict(variant) for variant in VARIANTS],
        "mss_max_delay_minutes": MAX_MSS_DELAY_MINUTES,
        "expiries": ORDER_EXPIRIES,
        "target_rs": TARGET_RS,
        "hold_minutes": PRIMARY_HOLD_MINUTES,
        "round_trip_costs": ROUND_TRIP_COSTS,
        "primary": {"expiry_minutes": PRIMARY_EXPIRY_MINUTES, "target_r": PRIMARY_TARGET_R, "cost": 0.0015},
        "selected_variant_from_2023": selected,
        "edge_gate_passed": has_edge,
        "conditional_hypothesis": {
            "variant": CONDITIONAL_VARIANT,
            "macro_timeframe": CONDITIONAL_TIMEFRAME,
            "minimum_risk_fraction": CONDITIONAL_MIN_RISK,
            "limit_expiry_minutes": CONDITIONAL_EXPIRY_MINUTES,
            "target_r": CONDITIONAL_TARGET_R,
            "passed": conditional_edge,
            "status": "post-broad-study hypothesis; requires a new forward/paper validation period",
        },
        "candidate_count": int(len(candidates)),
        "filled_first_touch_count": int(fills["first_fill_pos"].ge(0).sum()) if not fills.empty else 0,
        "notes": [
            "No data interface was written or accessed directly; all OHLC rows came from OKXTradeBarLoader.",
            "Macro pivots are calculated offline only to determine the timestamp at which they become observable; the scanner activates them no earlier than that timestamp.",
            "Same-bar target/stop intersections are assigned to stop first.",
        ],
    }
    (out_dir / "00_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
    return []


def run_self_test() -> None:
    index = pd.date_range("2024-01-01", periods=90, freq="1min")
    close = np.linspace(100.0, 102.0, len(index))
    bars = pd.DataFrame({"open": close, "high": close + 0.5, "low": close - 0.5, "close": close}, index=index)
    mask_high = pivot_mask(pd.Series([1, 2, 4, 2, 1], dtype=float), 1, high=True)
    mask_low = pivot_mask(pd.Series([4, 2, 1, 2, 4], dtype=float), 1, high=False)
    if not mask_high[2] or not mask_low[2]:
        raise AssertionError("symmetric pivot fixture failed")
    candidate = pd.DataFrame(
        [{
            "candidate_id": "fixture", "variant": "fixture", "year": 2024, "side": 1, "side_name": "LONG",
            "entry_limit": 101.0, "stop_price": 99.0, "risk_fraction": 2 / 101,
            "order_start_pos": 5, "order_start_time": index[5],
        }]
    )
    bars.loc[index[7], ["low", "high", "open", "close"]] = [100.5, 102.5, 101.2, 102.0]
    filled = attach_first_fills(candidate, bars, max_expiry=10)
    replay = replay_outcomes(filled, bars, expiries=(10,), targets=(1.0,), hold_minutes=20)
    if filled.loc[0, "first_fill_status"] != "FILLED" or replay.loc[0, "outcome"] != "TP":
        raise AssertionError("limit fill / TP fixture failed")
    print("[self-test] passed", flush=True)


def run(args: argparse.Namespace) -> Path:
    if args.self_test:
        run_self_test()
        return PROJECT_ROOT / args.out_dir
    bars = load_bars(args)
    research_start = pd.Timestamp(args.start_date)
    actual_end_exclusive = bars.index.max() + pd.Timedelta(minutes=1)
    if bars.index.min() > pd.Timestamp(args.warmup_start_date):
        raise RuntimeError("local data does not cover the requested warmup start")
    if actual_end_exclusive <= research_start:
        raise RuntimeError("no research-period bars returned by data_feed")
    print(f"[window] warmup={bars.index.min()} -> 2022-12-31; research={research_start} -> {bars.index.max()}", flush=True)

    levels_by_width: dict[int, pd.DataFrame] = {}
    for width in sorted({variant.macro_width for variant in VARIANTS}):
        levels = build_macro_levels(bars, width)
        if levels.empty:
            raise RuntimeError(f"no macro levels for width={width}")
        levels_by_width[width] = levels
        print(f"[levels] width={width} levels={len(levels):,}", flush=True)

    candidate_parts: list[pd.DataFrame] = []
    for variant in VARIANTS:
        print(f"[scan] {variant.name}", flush=True)
        part = scan_candidates(
            bars,
            levels_by_width[variant.macro_width],
            variant,
            research_start=research_start,
            research_end_exclusive=actual_end_exclusive,
        )
        print(f"[scan] {variant.name} candidates={len(part):,}", flush=True)
        if not part.empty:
            candidate_parts.append(part)
    candidates = pd.concat(candidate_parts, ignore_index=True) if candidate_parts else pd.DataFrame()
    if candidates.empty:
        raise RuntimeError("No causal sweep -> MSS -> FVG candidates. The requested pattern is not present under frozen definitions.")
    candidates["candidate_id"] = [f"{row.variant}_{idx:06d}" for idx, row in enumerate(candidates.itertuples(index=False))]
    print(f"[candidates] total={len(candidates):,}", flush=True)

    fills = attach_first_fills(candidates, bars, max(ORDER_EXPIRIES))
    outcomes = replay_outcomes(fills, bars)
    scorecard = build_scorecard(candidates, fills, outcomes)
    gates, selected, has_edge = select_edge(scorecard)
    print(f"[edge-gate] selected={selected} passed={has_edge}", flush=True)
    backtest = sequential_backtest(candidates, fills, outcomes, selected) if has_edge else pd.DataFrame()

    out_dir = PROJECT_ROOT / args.out_dir
    write_outputs(
        out_dir,
        args=args,
        bars=bars,
        levels_by_width=levels_by_width,
        candidates=candidates,
        fills=fills,
        outcomes=outcomes,
        scorecard=scorecard,
        gates=gates,
        selected=selected,
        has_edge=has_edge,
        backtest=backtest,
    )
    charts = [] if args.skip_charts else write_charts(out_dir, scorecard, selected)
    render_report(
        PROJECT_ROOT / "research/ict/mss/REPORT.md",
        bars=bars,
        coverage=coverage_table(bars),
        candidates=candidates,
        scorecard=scorecard,
        gates=gates,
        selected=selected,
        has_edge=has_edge,
        backtest=backtest,
        chart_files=charts,
    )
    print(f"[done] report={PROJECT_ROOT / 'research/ict/mss/REPORT.md'}", flush=True)
    print(f"[done] outputs={out_dir}", flush=True)
    return out_dir


if __name__ == "__main__":
    run(parse_args())
