#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
FVG Sweep Reclaim 3R - Footprint Support Lab
===========================================

This script takes the setups generated by ``fvg_sweep_reclaim_3r_research.py``
and tests a stricter causal entry idea:

    HTF FVG + 15m sweep + displacement + new 15m FVG already exists
    -> wait until 0.2% range bar trades back into the new FVG
    -> require range-footprint evidence that the new FVG is defended
    -> enter on the NEXT range bar open
    -> stop at sweep extreme +/- buffer, target fixed RR

Important causality rule:
    The footprint of the touch bar is only known after that range bar closes.
    Therefore confirmed-footprint entries are placed at the next range bar open,
    not inside the same footprint bar.

This is a filter/replay lab, not a production strategy.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data_feed.okx_range_bar_loader import OKXRangeBarLoader, range_code  # noqa: E402
from src.data_feed.okx_range_footprint_loader import OKXRangeFootprintLoader  # noqa: E402

SIDE_SIGN = {"long": 1, "short": -1}
SUPPORT_MODES = [
    "baseline_touch_next_open",
    "fp_delta_aligned",
    "fp_large_delta_aligned",
    "fp_absorption_reversal",
    "fp_rejection_close",
    "fp_any_support",
    "fp_strong_support_2of4",
]


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Replay FVG sweep setups only after causal range-footprint support inside the new FVG.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--input-dir", default="data/reports/research/fvg_sweep_reclaim_3r_both_htf_kline")
    p.add_argument("--symbol", default="ETH-USDT-SWAP")
    p.add_argument("--start-date", default="2023-01-01")
    p.add_argument("--end-date", default="2026-06-30")
    p.add_argument("--warmup-start-date", default="2022-01-01")
    p.add_argument("--out-dir", default="data/reports/research/fvg_sweep_reclaim_3r_fp_support")

    p.add_argument("--range-pct", type=float, default=0.0020)
    p.add_argument("--footprint-price-step", type=float, default=1.0)
    p.add_argument("--footprint-band-steps", type=int, default=2, help="Price bucket padding around the new FVG when reading footprint support.")

    p.add_argument("--side", choices=["long", "short", "both"], default="both")
    p.add_argument("--dedup-setups", action="store_true", default=True)
    p.add_argument("--no-dedup-setups", action="store_false", dest="dedup_setups")
    p.add_argument("--entry-wait-minutes", type=int, default=720)
    p.add_argument("--max-hold-minutes", type=int, default=4320)
    p.add_argument("--stop-buffer-pct", type=float, default=0.0003)
    p.add_argument("--rr", type=float, default=3.0)
    p.add_argument("--fee-rate", type=float, default=0.0011)
    p.add_argument("--slippage-pct", type=float, default=0.0002)
    p.add_argument("--same-bar-policy", choices=["conservative", "target", "unknown"], default="conservative")

    p.add_argument("--min-count", type=int, default=30)
    p.add_argument("--event-sample-size", type=int, default=100000)
    p.add_argument("--progress-every", type=int, default=250)
    return p.parse_args(argv)


def sides_from_arg(text: str) -> list[str]:
    if text == "both":
        return ["long", "short"]
    return [text]


def write_csv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False, encoding="utf-8-sig")


def profit_factor(x: Iterable[float]) -> float:
    s = pd.to_numeric(pd.Series(list(x)), errors="coerce").dropna()
    if s.empty:
        return float("nan")
    gp = float(s[s > 0].sum())
    gl = float(-s[s <= 0].sum())
    if gl <= 0:
        return float("inf") if gp > 0 else float("nan")
    return gp / gl


def top_winner_share(x: Iterable[float], n: int = 5) -> float:
    s = pd.to_numeric(pd.Series(list(x)), errors="coerce").dropna()
    wins = np.sort(s[s > 0].to_numpy(float))[::-1]
    if wins.size == 0:
        return float("nan")
    total = float(wins.sum())
    return float(wins[:n].sum() / total) if total > 0 else float("nan")


def summarize_returns(s: pd.Series, min_count: int = 0) -> dict[str, Any]:
    x = pd.to_numeric(s, errors="coerce").dropna()
    if x.empty:
        return {
            "count": 0,
            "eligible": False,
            "mean": np.nan,
            "median": np.nan,
            "win_rate": np.nan,
            "profit_factor": np.nan,
            "target_rate": np.nan,
            "stop_rate": np.nan,
            "timeout_rate": np.nan,
            "top5_winner_share": np.nan,
            "p05": np.nan,
            "p25": np.nan,
            "p75": np.nan,
            "p95": np.nan,
        }
    return {
        "count": int(len(x)),
        "eligible": bool(len(x) >= int(min_count)),
        "mean": float(x.mean()),
        "median": float(x.median()),
        "win_rate": float((x > 0).mean()),
        "profit_factor": profit_factor(x),
        "top5_winner_share": top_winner_share(x),
        "p05": float(x.quantile(0.05)),
        "p25": float(x.quantile(0.25)),
        "p75": float(x.quantile(0.75)),
        "p95": float(x.quantile(0.95)),
    }


def load_setups(input_dir: Path, args: argparse.Namespace) -> pd.DataFrame:
    path = input_dir / "02_sweep_new_fvg_setups.csv"
    if not path.exists():
        raise FileNotFoundError(f"missing setups file: {path}")
    df = pd.read_csv(path)
    if df.empty:
        return df
    sides = set(sides_from_arg(args.side))
    df = df[df["side"].astype(str).isin(sides)].copy()
    for c in ["sweep_signal_time", "new_fvg_available_time", "sweep_bar_start", "confirm_bar_start"]:
        if c in df.columns:
            df[c] = pd.to_datetime(df[c], errors="coerce")
    for c in [
        "new_fvg_lower", "new_fvg_upper", "new_fvg_mid", "sweep_low", "sweep_high", "sweep_extreme",
        "htf_fvg_width_pct", "new_fvg_width_pct", "impulse_ret_from_sweep_close", "sig_atr_20_pct", "sig_ret_8",
    ]:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")
    df = df.dropna(subset=["new_fvg_available_time", "new_fvg_lower", "new_fvg_upper", "side"])
    df = df[pd.to_datetime(df["new_fvg_available_time"]) >= pd.Timestamp(args.start_date)].copy()
    df = df[pd.to_datetime(df["new_fvg_available_time"]) <= pd.Timestamp(args.end_date) + pd.Timedelta(days=1)].copy()
    if bool(args.dedup_setups) and not df.empty:
        before = len(df)
        # Remove duplicate variants created by multiple sweep lookbacks for the same actual setup.
        df["_fvg_lower_r"] = df["new_fvg_lower"].round(6)
        df["_fvg_upper_r"] = df["new_fvg_upper"].round(6)
        df["_sweep_low_r"] = df["sweep_low"].round(6)
        df["_sweep_high_r"] = df["sweep_high"].round(6)
        key = ["side", "new_fvg_available_time", "_fvg_lower_r", "_fvg_upper_r", "_sweep_low_r", "_sweep_high_r"]
        df = df.sort_values(["new_fvg_available_time", "side", "setup_id"]).drop_duplicates(key, keep="first").copy()
        df = df.drop(columns=[c for c in df.columns if c.startswith("_")])
        print(f"[setups] dedup {before:,} -> {len(df):,}", flush=True)
    df = df.sort_values(["new_fvg_available_time", "side", "setup_id"]).reset_index(drop=True)
    return df


def load_range_bars(args: argparse.Namespace) -> pd.DataFrame:
    print(f"[load] range bars {args.symbol} {range_code(args.range_pct)} {args.warmup_start_date}->{args.end_date}", flush=True)
    df = OKXRangeBarLoader(symbol=args.symbol, range_pct=float(args.range_pct)).fetch_data_by_date_range(
        args.warmup_start_date, args.end_date, cvd_mode="range"
    )
    if df.empty:
        raise RuntimeError("No range bars loaded.")
    out = df.reset_index(drop=True).copy()
    for c in ["start_ts", "end_ts"]:
        out[c] = pd.to_datetime(out[c], errors="coerce")
    out = out.dropna(subset=["start_ts", "end_ts"])
    out["bar_id"] = pd.to_numeric(out["bar_id"], errors="coerce").astype("Int64")
    out = out.dropna(subset=["bar_id"])
    out["bar_id"] = out["bar_id"].astype("int64")
    for c in ["open", "high", "low", "close", "direction", "notional", "delta_notional", "large_delta_notional", "taker_buy_ratio"]:
        if c in out.columns:
            out[c] = pd.to_numeric(out[c], errors="coerce")
    out = out.dropna(subset=["open", "high", "low", "close"])
    out = out.sort_values(["end_ts", "bar_id"]).reset_index(drop=True)
    print(f"       rows={len(out):,} range={out['end_ts'].min()} -> {out['end_ts'].max()}", flush=True)
    return out


def load_footprints(args: argparse.Namespace) -> dict[int, pd.DataFrame]:
    print(f"[load] range footprints {args.symbol} {range_code(args.range_pct)} step={args.footprint_price_step}", flush=True)
    fp = OKXRangeFootprintLoader(
        symbol=args.symbol,
        range_pct=float(args.range_pct),
        price_step=float(args.footprint_price_step),
    ).fetch_data_by_date_range(args.warmup_start_date, args.end_date)
    if fp.empty:
        raise RuntimeError("No range footprint rows loaded. Build footprint DB first.")
    for c in ["bar_id", "price_bucket"]:
        fp[c] = pd.to_numeric(fp[c], errors="coerce")
    fp = fp.dropna(subset=["bar_id", "price_bucket"])
    fp["bar_id"] = fp["bar_id"].astype("int64")
    for c in [
        "notional", "buy_notional", "sell_notional", "delta_notional", "large_buy_notional",
        "large_sell_notional", "large_delta_notional", "trades_count", "large_trades_count", "max_trade_notional",
    ]:
        if c in fp.columns:
            fp[c] = pd.to_numeric(fp[c], errors="coerce").fillna(0.0)
    fp = fp.sort_values(["bar_id", "price_bucket"]).reset_index(drop=True)
    print(f"       rows={len(fp):,} bars={fp['bar_id'].nunique():,}", flush=True)
    # Dictionary is fast enough here because one range bar usually has few price buckets.
    return {int(k): g.copy() for k, g in fp.groupby("bar_id", sort=False)}


def footprint_support_flags(side: str, setup: pd.Series, bar: pd.Series, fp_bar: pd.DataFrame | None, args: argparse.Namespace) -> dict[str, Any]:
    sign = SIDE_SIGN[side]
    lower = float(setup["new_fvg_lower"])
    upper = float(setup["new_fvg_upper"])
    mid = float(setup.get("new_fvg_mid", (lower + upper) / 2.0))
    step_pad = max(0, int(args.footprint_band_steps)) * float(args.footprint_price_step)
    if fp_bar is None or fp_bar.empty:
        return {
            "fp_has_rows": False,
            "fp_band_rows": 0,
            "fp_band_notional": 0.0,
            "fp_band_delta": np.nan,
            "fp_band_large_delta": np.nan,
            "fp_band_buy_notional": np.nan,
            "fp_band_sell_notional": np.nan,
            "fp_delta_aligned": False,
            "fp_large_delta_aligned": False,
            "fp_absorption_reversal": False,
            "fp_rejection_close": False,
            "fp_any_support": False,
            "fp_strong_support_2of4": False,
        }
    buckets = pd.to_numeric(fp_bar["price_bucket"], errors="coerce")
    band = fp_bar[(buckets >= lower - step_pad) & (buckets <= upper + step_pad)].copy()
    if band.empty:
        # Fallback: use the whole touched range bar footprint, but flag rows=0 so report is transparent.
        band = fp_bar.copy()
        band_rows = 0
    else:
        band_rows = int(len(band))
    band_notional = float(pd.to_numeric(band.get("notional", 0.0), errors="coerce").fillna(0.0).sum())
    band_delta = float(pd.to_numeric(band.get("delta_notional", 0.0), errors="coerce").fillna(0.0).sum())
    band_large_delta = float(pd.to_numeric(band.get("large_delta_notional", 0.0), errors="coerce").fillna(0.0).sum())
    band_buy = float(pd.to_numeric(band.get("buy_notional", 0.0), errors="coerce").fillna(0.0).sum())
    band_sell = float(pd.to_numeric(band.get("sell_notional", 0.0), errors="coerce").fillna(0.0).sum())
    op = float(bar["open"])
    cl = float(bar["close"])
    bar_up = cl > op
    bar_down = cl < op
    if side == "long":
        delta_aligned = band_delta > 0
        large_aligned = band_large_delta > 0
        # Aggressive sells into FVG, but range bar closes up / rejects lower prices.
        absorption = (band_delta < 0) and bar_up
        rejection = cl >= mid
    else:
        delta_aligned = band_delta < 0
        large_aligned = band_large_delta < 0
        # Aggressive buys into FVG, but range bar closes down / rejects higher prices.
        absorption = (band_delta > 0) and bar_down
        rejection = cl <= mid
    positives = [bool(delta_aligned), bool(large_aligned), bool(absorption), bool(rejection)]
    return {
        "fp_has_rows": True,
        "fp_band_rows": band_rows,
        "fp_band_notional": band_notional,
        "fp_band_delta": band_delta,
        "fp_band_large_delta": band_large_delta,
        "fp_band_buy_notional": band_buy,
        "fp_band_sell_notional": band_sell,
        "fp_delta_aligned": bool(delta_aligned),
        "fp_large_delta_aligned": bool(large_aligned),
        "fp_absorption_reversal": bool(absorption),
        "fp_rejection_close": bool(rejection),
        "fp_any_support": bool(any(positives)),
        "fp_strong_support_2of4": bool(sum(int(x) for x in positives) >= 2),
    }


def replay_from_entry(
    setup: pd.Series,
    bars: pd.DataFrame,
    entry_pos: int,
    support_pos: int,
    mode: str,
    flags: dict[str, Any],
    args: argparse.Namespace,
) -> dict[str, Any]:
    side = str(setup["side"])
    sign = SIDE_SIGN[side]
    rr = float(args.rr)
    fee = float(args.fee_rate)
    slip = float(args.slippage_pct)
    max_hold = pd.Timedelta(minutes=int(args.max_hold_minutes))

    if entry_pos >= len(bars):
        return {}
    b_entry = bars.iloc[entry_pos]
    entry_time = pd.Timestamp(b_entry["start_ts"])
    entry_available_time = pd.Timestamp(b_entry["end_ts"])
    support_signal_time = pd.Timestamp(bars.iloc[support_pos]["end_ts"])
    if entry_time < support_signal_time:
        return {}
    if side == "long":
        entry_price = float(b_entry["open"] * (1.0 + slip))
        stop_price = float(float(setup["sweep_low"]) * (1.0 - float(args.stop_buffer_pct)) * (1.0 - slip))
        if not (np.isfinite(entry_price) and np.isfinite(stop_price) and stop_price < entry_price):
            return {}
        risk = entry_price - stop_price
        target_price = entry_price + rr * risk
    else:
        entry_price = float(b_entry["open"] * (1.0 - slip))
        stop_price = float(float(setup["sweep_high"]) * (1.0 + float(args.stop_buffer_pct)) * (1.0 + slip))
        if not (np.isfinite(entry_price) and np.isfinite(stop_price) and stop_price > entry_price):
            return {}
        risk = stop_price - entry_price
        target_price = entry_price - rr * risk
        if target_price <= 0:
            return {}
    max_exit_time = entry_time + max_hold
    times = pd.to_datetime(bars["start_ts"]).to_numpy(dtype="datetime64[ns]")
    end_pos = int(np.searchsorted(times, np.datetime64(max_exit_time), side="right"))
    end_pos = min(end_pos, len(bars))
    if end_pos <= entry_pos:
        return {}
    exit_reason = "TIMEOUT"
    exit_pos = end_pos - 1
    same_bar_both = False
    for pos in range(entry_pos, end_pos):
        high = float(bars.iloc[pos]["high"])
        low = float(bars.iloc[pos]["low"])
        if side == "long":
            hit_stop = low <= stop_price
            hit_target = high >= target_price
        else:
            hit_stop = high >= stop_price
            hit_target = low <= target_price
        if hit_stop and hit_target:
            same_bar_both = True
            if args.same_bar_policy == "target":
                exit_reason = "TARGET"
            elif args.same_bar_policy == "unknown":
                exit_reason = "BOTH_UNKNOWN"
            else:
                exit_reason = "STOP"
            exit_pos = pos
            break
        if hit_stop:
            exit_reason = "STOP"
            exit_pos = pos
            break
        if hit_target:
            exit_reason = "TARGET"
            exit_pos = pos
            break
    b_exit = bars.iloc[exit_pos]
    if exit_reason == "TARGET":
        exit_price = target_price * (1.0 - slip) if side == "long" else target_price * (1.0 + slip)
    elif exit_reason == "STOP":
        exit_price = stop_price * (1.0 - slip) if side == "long" else stop_price * (1.0 + slip)
    else:
        exit_price = float(b_exit["close"] * (1.0 - slip)) if side == "long" else float(b_exit["close"] * (1.0 + slip))
    gross = float(sign * (exit_price / entry_price - 1.0))
    net = gross - fee
    path = bars.iloc[entry_pos:end_pos]
    if side == "long":
        mfe = float(path["high"].max() / entry_price - 1.0)
        mae = float(path["low"].min() / entry_price - 1.0)
    else:
        mfe = float(1.0 - path["low"].min() / entry_price)
        mae = float(1.0 - path["high"].max() / entry_price)
    out = setup.to_dict()
    out.update(flags)
    out.update({
        "support_mode": mode,
        "support_bar_id": int(bars.iloc[support_pos]["bar_id"]),
        "support_bar_start": pd.Timestamp(bars.iloc[support_pos]["start_ts"]),
        "support_signal_time": support_signal_time,
        "support_bar_open": float(bars.iloc[support_pos]["open"]),
        "support_bar_high": float(bars.iloc[support_pos]["high"]),
        "support_bar_low": float(bars.iloc[support_pos]["low"]),
        "support_bar_close": float(bars.iloc[support_pos]["close"]),
        "entry_axis": "range_fp_next_open",
        "filled": True,
        "entry_time": entry_time,
        "entry_available_time": entry_available_time,
        "entry_price": entry_price,
        "stop_price": stop_price,
        "target_price": target_price,
        "risk_pct": float(risk / entry_price),
        "exit_bar_start": pd.Timestamp(b_exit["start_ts"]),
        "exit_time": pd.Timestamp(b_exit["end_ts"]),
        "exit_price": float(exit_price),
        "exit_reason": exit_reason,
        "same_bar_both_hit_flag": bool(same_bar_both),
        "gross_return": gross,
        "net_return": net,
        "mfe": mfe,
        "mae": mae,
        "r_multiple_gross": float(gross / (risk / entry_price)) if risk > 0 else np.nan,
        "bars_held_on_axis": int(exit_pos - entry_pos + 1),
        "minutes_to_support": float((support_signal_time - pd.Timestamp(setup["new_fvg_available_time"])).total_seconds() / 60.0),
        "minutes_held": float((pd.Timestamp(b_exit["end_ts"]) - entry_time).total_seconds() / 60.0),
    })
    return out


def mode_passes(mode: str, flags: dict[str, Any]) -> bool:
    if mode == "baseline_touch_next_open":
        return True
    return bool(flags.get(mode, False))


def run_replay(setups: pd.DataFrame, bars: pd.DataFrame, fp_by_bar: dict[int, pd.DataFrame], args: argparse.Namespace) -> pd.DataFrame:
    if setups.empty:
        return pd.DataFrame()
    rb = bars.sort_values("start_ts").reset_index(drop=True).copy()
    rb_times = pd.to_datetime(rb["start_ts"]).to_numpy(dtype="datetime64[ns]")
    rows: list[dict[str, Any]] = []
    entry_wait = pd.Timedelta(minutes=int(args.entry_wait_minutes))
    progress_every = max(1, int(args.progress_every))
    for n, (_, s) in enumerate(setups.iterrows(), start=1):
        if n == 1 or n % progress_every == 0 or n == len(setups):
            print(f"[replay] setups {n:,}/{len(setups):,} trades={len(rows):,}", flush=True)
        start_time = pd.Timestamp(s["new_fvg_available_time"])
        deadline = start_time + entry_wait
        start_pos = int(np.searchsorted(rb_times, np.datetime64(start_time), side="left"))
        deadline_pos = int(np.searchsorted(rb_times, np.datetime64(deadline), side="right"))
        if start_pos >= len(rb) or deadline_pos <= start_pos:
            continue
        side = str(s["side"])
        lower = float(s["new_fvg_lower"])
        upper = float(s["new_fvg_upper"])
        touched_modes: dict[str, dict[str, Any]] = {}
        for pos in range(start_pos, deadline_pos):
            b = rb.iloc[pos]
            if float(b["high"]) < lower or float(b["low"]) > upper:
                continue
            bar_id = int(b["bar_id"])
            flags = footprint_support_flags(side, s, b, fp_by_bar.get(bar_id), args)
            for mode in SUPPORT_MODES:
                if mode in touched_modes:
                    continue
                if mode_passes(mode, flags):
                    touched_modes[mode] = {"support_pos": pos, "flags": flags}
            if len(touched_modes) == len(SUPPORT_MODES):
                break
        for mode, info in touched_modes.items():
            support_pos = int(info["support_pos"])
            entry_pos = support_pos + 1  # Causal: support footprint known only after support bar closes.
            trade = replay_from_entry(s, rb, entry_pos, support_pos, mode, info["flags"], args)
            if trade:
                rows.append(trade)
    return pd.DataFrame(rows)


def summarize_trades(trades: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    if trades.empty:
        return pd.DataFrame()
    filled = trades[trades.get("filled", False).astype(bool)].copy()
    rows: list[dict[str, Any]] = []
    group_cols = ["side", "support_mode"]
    for keys, g in filled.groupby(group_cols, dropna=False):
        side, mode = keys
        row: dict[str, Any] = {"side": side, "support_mode": mode}
        row.update(summarize_returns(g["net_return"], int(args.min_count)))
        row["target_rate"] = float((g["exit_reason"] == "TARGET").mean())
        row["stop_rate"] = float((g["exit_reason"] == "STOP").mean())
        row["timeout_rate"] = float((g["exit_reason"] == "TIMEOUT").mean())
        row["avg_risk_pct"] = float(pd.to_numeric(g["risk_pct"], errors="coerce").mean())
        row["median_minutes_to_support"] = float(pd.to_numeric(g["minutes_to_support"], errors="coerce").median())
        rows.append(row)
    # Combined rows by support mode.
    for mode, g in filled.groupby("support_mode", dropna=False):
        row = {"side": "combined", "support_mode": mode}
        row.update(summarize_returns(g["net_return"], int(args.min_count)))
        row["target_rate"] = float((g["exit_reason"] == "TARGET").mean())
        row["stop_rate"] = float((g["exit_reason"] == "STOP").mean())
        row["timeout_rate"] = float((g["exit_reason"] == "TIMEOUT").mean())
        row["avg_risk_pct"] = float(pd.to_numeric(g["risk_pct"], errors="coerce").mean())
        row["median_minutes_to_support"] = float(pd.to_numeric(g["minutes_to_support"], errors="coerce").median())
        rows.append(row)
    out = pd.DataFrame(rows)
    return out.sort_values(["eligible", "profit_factor", "mean", "count"], ascending=[False, False, False, False]).reset_index(drop=True)


def yearly_summary(trades: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    if trades.empty:
        return pd.DataFrame()
    filled = trades[trades.get("filled", False).astype(bool)].copy()
    filled["year"] = pd.to_datetime(filled["entry_time"], errors="coerce").dt.year
    rows: list[dict[str, Any]] = []
    for (side, mode, year), g in filled.groupby(["side", "support_mode", "year"], dropna=False):
        row = {"side": side, "support_mode": mode, "year": int(year) if pd.notna(year) else year}
        row.update(summarize_returns(g["net_return"], 0))
        row["target_rate"] = float((g["exit_reason"] == "TARGET").mean())
        row["stop_rate"] = float((g["exit_reason"] == "STOP").mean())
        rows.append(row)
    return pd.DataFrame(rows).sort_values(["side", "support_mode", "year"]).reset_index(drop=True)


def build_funnel(setups: pd.DataFrame, trades: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    rows.append({"stage": "input_setups", "side": "combined", "count": int(len(setups))})
    for side, g in setups.groupby("side", dropna=False):
        rows.append({"stage": "input_setups", "side": side, "count": int(len(g))})
    if not trades.empty:
        for mode, g in trades.groupby("support_mode", dropna=False):
            rows.append({"stage": "filled_trades", "side": "combined", "support_mode": mode, "count": int(len(g))})
            for side, gg in g.groupby("side", dropna=False):
                rows.append({"stage": "filled_trades", "side": side, "support_mode": mode, "count": int(len(gg))})
    return pd.DataFrame(rows)


def build_audit(setups: pd.DataFrame, bars: pd.DataFrame, trades: pd.DataFrame, meta: dict[str, Any]) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    rows.append({"check": "ordinary_kline_used_for_signal_or_entry", "value": 0})
    rows.append({"check": "uses_range_footprint", "value": 1})
    rows.append({"check": "entry_axis_is_range_next_open", "value": 1})
    if not trades.empty:
        filled = trades[trades.get("filled", False).astype(bool)].copy()
        rows.append({"check": "entry_before_support_signal", "value": int((pd.to_datetime(filled["entry_time"]) < pd.to_datetime(filled["support_signal_time"])).sum())})
        rows.append({"check": "entry_before_new_fvg_available", "value": int((pd.to_datetime(filled["entry_time"]) < pd.to_datetime(filled["new_fvg_available_time"])).sum())})
        rows.append({"check": "exit_before_entry", "value": int((pd.to_datetime(filled["exit_time"]) < pd.to_datetime(filled["entry_time"])).sum())})
        rows.append({"check": "same_bar_both_hit", "value": int(pd.to_numeric(filled.get("same_bar_both_hit_flag", False), errors="coerce").fillna(0).sum())})
        rows.append({"check": "missing_footprint_rows_on_fp_modes", "value": int(((filled["support_mode"] != "baseline_touch_next_open") & (~filled["fp_has_rows"].astype(bool))).sum())})
    for k, v in meta.items():
        rows.append({"check": str(k), "value": v})
    return pd.DataFrame(rows)


def make_brief(args: argparse.Namespace, summary: pd.DataFrame, yearly: pd.DataFrame, funnel: pd.DataFrame, audit: pd.DataFrame) -> str:
    lines: list[str] = []
    lines.append("# FVG Footprint Support Lab Brief")
    lines.append("")
    lines.append("## Scope")
    lines.append(f"- input_dir: `{args.input_dir}`")
    lines.append(f"- symbol: `{args.symbol}`")
    lines.append(f"- side: `{args.side}`")
    lines.append(f"- range footprint: range_pct=`{args.range_pct}`, price_step=`{args.footprint_price_step}`")
    lines.append("- entry rule: range bar touches new 15m FVG, footprint support is confirmed at range bar close, then enter on next range bar open.")
    lines.append(f"- RR={args.rr}:1; fee={args.fee_rate:.4%}; slippage one-way={args.slippage_pct:.4%}")
    lines.append("")
    lines.append("## Funnel")
    lines.append("No funnel output." if funnel.empty else funnel.to_markdown(index=False))
    lines.append("")
    lines.append("## Audit")
    lines.append("No audit output." if audit.empty else audit.head(80).to_markdown(index=False))
    lines.append("")
    lines.append("## Support-mode summary")
    if summary.empty:
        lines.append("No trades generated.")
    else:
        cols = ["side", "support_mode", "count", "mean", "median", "win_rate", "profit_factor", "target_rate", "stop_rate", "top5_winner_share", "avg_risk_pct", "median_minutes_to_support"]
        lines.append(summary[[c for c in cols if c in summary.columns]].to_markdown(index=False))
    lines.append("")
    lines.append("## Notes")
    lines.append("- `baseline_touch_next_open` is a fairer baseline for this lab: first FVG touch, then next range open, without requiring footprint support.")
    lines.append("- Footprint support modes are causal because the entry waits until the support range bar closes.")
    lines.append("- If footprint support improves PF/target_rate versus baseline but sample collapses, treat it as a filter candidate, not a strategy.")
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    setups = load_setups(Path(args.input_dir), args)
    print(f"[setups] rows={len(setups):,}", flush=True)
    bars = load_range_bars(args)
    fp_by_bar = load_footprints(args)

    trades = run_replay(setups, bars, fp_by_bar, args)
    print(f"[trades] rows={len(trades):,}", flush=True)

    sample_trades = trades.head(int(args.event_sample_size)) if not trades.empty else pd.DataFrame()
    summary = summarize_trades(trades, args)
    yearly = yearly_summary(trades, args)
    funnel = build_funnel(setups, trades)
    meta = {
        "input_setups": int(len(setups)),
        "range_rows": int(len(bars)),
        "footprint_bars_loaded": int(len(fp_by_bar)),
        "trade_rows": int(len(trades)),
        "support_modes": ",".join(SUPPORT_MODES),
        "dedup_setups": bool(args.dedup_setups),
    }
    audit = build_audit(setups, bars, trades, meta)

    write_csv(setups.head(int(args.event_sample_size)), out_dir / "00_input_setups_sample.csv")
    write_csv(sample_trades, out_dir / "01_fp_support_trades_sample.csv")
    write_csv(summary, out_dir / "02_support_variant_summary.csv")
    write_csv(yearly, out_dir / "03_yearly_summary.csv")
    write_csv(funnel, out_dir / "04_funnel.csv")
    write_csv(audit, out_dir / "05_causal_audit.csv")
    (out_dir / "09_meta.json").write_text(json.dumps({**vars(args), **meta}, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
    (out_dir / "20_research_brief.md").write_text(make_brief(args, summary, yearly, funnel, audit), encoding="utf-8")

    print(f"[done] wrote reports to {out_dir}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
