#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""ETH Portfolio V1: LF V10B + Low Sweep V1 MF overlay backtest.

This is a portfolio-layer backtest wrapper, not a live-trading strategy.  It
combines two already frozen single-strategy candidates:

    LF sleeve: ETH LF Portfolio V10B all-swing structural stop
    MF sleeve: Low Sweep V1 A0 + footprint + next_open + time48

The MF sleeve is tested both with the current V1 main exit and with the comfort
exit (mfe_lock_15_05_time48).  This file intentionally does not change either
child strategy's signal, entry, exit, stop, or fee logic.  It only studies
portfolio allocation/overlay rules.

Causal scope:
- Child trades are generated by their existing causal backtest functions.
- This portfolio layer only consumes already simulated trades.
- Portfolio returns are closed-trade event-level compounding, suitable for an
  initial overlay/sizing screen.  It does not mark open positions intrabar.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace
from typing import Iterable, Sequence

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backtest.lf import eth_lf_portfolio_v10a_momentum_micro_short_speed_filter_backtest as v10a  # noqa: E402
from backtest.lf import eth_lf_portfolio_v10b_all_swing_structural_stop_backtest as v10b  # noqa: E402
from backtest.mf.low_sweep import low_sweep_V1_a0_footprint_backtest as low_v1  # noqa: E402
from research.low_sweep_a_upgrade_research import UpgradeVariant, parse_stop_specs, write_csv  # noqa: E402
from src.utils.report import print_full_report  # noqa: E402

SCRIPT_NAME = "eth_portfolio_V1_lf_v10b_low_sweep_mf_backtest"
REPORT_STRATEGY_NAME = "ETH_Portfolio_V1_LF_V10B_LowSweepMF"
DEFAULT_OUT_DIR = "data/reports/backtest/portfolio/ETH_portfolio_V1_lf_v10b_low_sweep_mf"

LF_LEG = "LF_V10B"
MF_TIME48_LEG = "MF_LOW_SWEEP_TIME48"
MF_COMFORT_LEG = "MF_LOW_SWEEP_MFE_LOCK_15_05"
PRIMARY_SCENARIO = "portfolio_v1_lf100_mf150_time48_independent"
DEFAULT_LEVERAGE = 15.0


@dataclass(frozen=True)
class PortfolioScenario:
    scenario_name: str
    mf_variant_name: str
    mf_exposure: float
    conflict_mode: str
    lf_weight: float = 1.0
    guard_mode: str = "none"
    margin_cap: float | None = None
    notional_cap: float | None = None
    min_mf_exposure: float = 0.05


def _parse_float_list(raw: str) -> list[float]:
    out: list[float] = []
    for part in str(raw).split(","):
        part = part.strip()
        if not part:
            continue
        value = float(part)
        if math.isfinite(value):
            out.append(value)
    return sorted(set(out))


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="ETH Portfolio V1 LF+MF overlay backtest")
    p.add_argument("--symbol", default="ETH-USDT-SWAP")
    p.add_argument("--start-date", default="2023-01-01")
    p.add_argument("--end-date", default="2026-06-30")
    p.add_argument("--warmup-start-date", default="2022-01-01")
    p.add_argument("--initial-capital", type=float, default=1000.0)
    p.add_argument("--leverage", type=float, default=DEFAULT_LEVERAGE, help="Execution leverage used only to report margin usage; sizing is based on notional exposure.")
    p.add_argument("--out-dir", default=DEFAULT_OUT_DIR)

    # Portfolio overlay sizing.  1.5 corresponds to 10% margin with 15x leverage
    # if the margin is interpreted as 10% of total account equity.
    p.add_argument("--lf-weight", type=float, default=1.0, help="Portfolio weight applied to the LF sleeve returns.")
    p.add_argument("--mf-exposures", default="0.5,1.0,1.5", help="Comma list of MF notional exposure multiples of portfolio equity.")
    p.add_argument(
        "--conflict-modes",
        default="independent",
        help="Comma list. Default is independent because LF V10B and MF Low Sweep are separate sleeves; optional diagnostics: skip_when_lf_active,skip_if_lf_short.",
    )
    p.add_argument(
        "--guard-modes",
        default="none,margin80,margin85,notional12,notional13,margin85_notional13",
        help=(
            "Comma list of portfolio-level MF sizing guards. "
            "none keeps fixed MF exposure; marginXX caps total estimated margin fraction; "
            "notionalXX caps total LF+MF notional; marginXX_notionalYY applies both."
        ),
    )
    p.add_argument("--guard-margin-cap", type=float, default=0.85, help="Fallback margin cap used by custom guard modes.")
    p.add_argument("--guard-notional-cap", type=float, default=13.0, help="Fallback total notional cap used by custom guard modes.")
    p.add_argument("--min-mf-exposure", type=float, default=0.05, help="Skip a guarded MF trade if the remaining allowed exposure is below this notional multiple.")
    p.add_argument("--primary-scenario", default=PRIMARY_SCENARIO)
    p.add_argument("--skip-full-report", action="store_true")
    p.add_argument("--save-combined-trades", type=int, default=200000)

    # Child strategy knobs are deliberately minimal.  They mirror the current
    # formal candidates and should not be optimized in this portfolio wrapper.
    p.add_argument("--lf-preset", default="turbo")
    p.add_argument("--lf-bear-preset", default="high")
    p.add_argument("--lf-bull-preset", default="high")
    p.add_argument("--lf-priority-mode", default="reclaim_first")
    p.add_argument("--lf-global-risk-scale", type=float, default=1.30)
    p.add_argument("--lf-micro-filter-mode", default="soft")
    return p.parse_args(argv)


def _split_csv(raw: str) -> list[str]:
    return [x.strip() for x in str(raw).split(",") if x.strip()]


def _build_lf_args(args: argparse.Namespace) -> argparse.Namespace:
    """Build a V10B-compatible args namespace without parsing global sys.argv."""

    return SimpleNamespace(
        symbol=args.symbol,
        start_date=args.start_date,
        end_date=args.end_date,
        warmup_start_date=args.warmup_start_date,
        warmup_days=365,
        initial_capital=float(args.initial_capital),
        preset=args.lf_preset,
        unit_risk_per_trade=None,
        max_total_notional_mult=None,
        max_units=None,
        min_risk_mult=0.35,
        max_risk_mult=None,
        fee_rate=0.00055,
        slippage_pct=0.0002,
        disable_short=False,
        bear_preset=args.lf_bear_preset,
        bear_min_risk_mult=0.25,
        bear_standalone_risk_scale=1.0,
        bear_standalone_quality_scale=1.0,
        disable_bear_standalone=False,
        bull_preset=args.lf_bull_preset,
        bull_min_risk_mult=0.25,
        bull_reclaim_risk_scale=1.0,
        bull_reclaim_quality_scale=1.0,
        bull_execution_mode="inherit",
        disable_bull_reclaim=False,
        priority_mode=args.lf_priority_mode,
        global_risk_scale=float(args.lf_global_risk_scale),
        quality_mult_cap=2.20,
        micro_filter_mode=args.lf_micro_filter_mode,
        range_pct=0.002,
        price_step=1.0,
        range_data_dir=None,
        disable_footprint_context=False,
        micro_min_range_bars=5,
        micro_contra_imbalance=0.05,
        micro_aligned_imbalance=0.05,
        micro_bad_close_pos=0.35,
        micro_good_close_pos=0.65,
        micro_contra_risk_scale=0.50,
        micro_not_aligned_risk_scale=0.50,
        range_exit_mode="soft",
        range_exit_min_mfe_r=2.0,
        range_exit_giveback_frac=0.65,
        range_exit_min_hold_bars=2,
        range_exit_delay_bars=0,
        range_exit_contra_imbalance=0.05,
        range_exit_bad_close_pos=0.35,
        range_exit_require_reversal=True,
        disable_momentum_long_not_aligned_block=False,
        disable_momentum_short_fast_speed_block=False,
        rf_speed_rolling_window_bars=1080,
        rf_speed_min_periods=100,
        rf_speed_fast_quantile=0.75,
        out_dir=None,
    )


def run_lf_v10b_leg(args: argparse.Namespace) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Run the frozen LF V10B child backtest and return normalized trades."""

    lf_args = _build_lf_args(args)
    mom_cfg = v10a.make_momentum_config(lf_args)
    bear_cfg = v10a.make_bear_config(lf_args)
    bull_cfg = v10a.make_bull_config(lf_args)
    exec_cfg = v10a.make_exec_config(mom_cfg)
    bull_exec_cfg = v10a.bull_to_exec_config(bull_cfg) if lf_args.bull_execution_mode == "own" else exec_cfg

    trade_start = pd.Timestamp(args.start_date)
    load_start = pd.Timestamp(args.warmup_start_date or args.start_date)
    load_start_str = load_start.strftime("%Y-%m-%d")

    print(f"[lf] load 4H {args.symbol} {load_start_str}->{args.end_date}; trade_start={args.start_date}", flush=True)
    base = v10a.load_data(args.symbol, load_start_str, args.end_date, "4H")
    momentum = v10a.build_momentum_features(base, mom_cfg)
    bear = v10a.build_bear_features(base, bear_cfg)
    bull = v10a.build_bull_features(base, bull_cfg)
    micro_ctx = v10a.load_range_footprint_context(lf_args, load_start_str, args.end_date)
    momentum = v10a.apply_momentum_long_not_aligned_block(momentum, micro_ctx, lf_args)
    momentum = v10a.apply_momentum_short_fast_speed_block(momentum, micro_ctx, lf_args)
    features = v10a.select_portfolio_signals(momentum, bear, bull, lf_args)
    features = v10a.apply_micro_context_filter(features, micro_ctx, lf_args)
    features = v10b.add_structural_columns(features, lookback_bars=v10b.V10B_STRUCTURAL_STOP.lookback_bars)
    features = features.loc[trade_start : pd.Timestamp(args.end_date)].copy()

    trades, equity = v10b.run_v10b_backtest(
        features,
        exec_cfg,
        engine_cfgs={"MOMENTUM_V3": exec_cfg, "BEAR_V3_ONLY": exec_cfg, "BULL_RECLAIM_V2": bull_exec_cfg},
        global_risk_scale=lf_args.global_risk_scale,
        args=lf_args,
    )
    trades = v10a.attach_engine_to_trades(trades, features)
    out = pd.DataFrame(trades)
    if out.empty:
        return pd.DataFrame(), equity
    out = out.copy()
    out["strategy_leg"] = LF_LEG
    out["variant_name"] = LF_LEG
    out["entry_time"] = pd.to_datetime(out["entry_time"], errors="coerce")
    out["exit_time"] = pd.to_datetime(out["exit_time"], errors="coerce")
    out["side"] = pd.to_numeric(out.get("side", np.nan), errors="coerce")
    out["return_on_sleeve"] = pd.to_numeric(out.get("return_pct", out.get("pnl", 0.0)), errors="coerce")
    # If a legacy row somehow lacks return_pct, fall back to pnl/capital-before.
    if "return_pct" not in out.columns and {"pnl", "capital"}.issubset(out.columns):
        cap_after = pd.to_numeric(out["capital"], errors="coerce")
        pnl = pd.to_numeric(out["pnl"], errors="coerce")
        out["return_on_sleeve"] = pnl / (cap_after - pnl).replace(0, np.nan)
    out["exit_reason"] = out.get("note", "")
    out = attach_lf_position_metrics(out)
    return out.dropna(subset=["entry_time", "exit_time", "return_on_sleeve"]), equity


def _safe_float(value: object, default: float = float("nan")) -> float:
    try:
        out = float(value)
    except (TypeError, ValueError):
        return default
    return out if math.isfinite(out) else default


def _safe_side_from_row(row: pd.Series, default: int = 1) -> int:
    raw = row.get("side", np.nan)
    side = _safe_float(raw, float("nan"))
    if math.isfinite(side) and side != 0:
        return int(np.sign(side))
    typ = str(row.get("type", "")).upper()
    if "SHORT" in typ:
        return -1
    if "LONG" in typ:
        return 1
    leg = str(row.get("strategy_leg", ""))
    if leg.startswith("MF_LOW_SWEEP"):
        return 1
    return int(default)


def attach_lf_position_metrics(trades: pd.DataFrame) -> pd.DataFrame:
    """Attach actual LF notional/risk metrics from V10B closed trades.

    V10B sizing is risk-budget based, not a fixed notional percentage.  These
    diagnostics translate each closed trade into realized notional exposure
    versus the sleeve equity at entry.  They are portfolio-report fields only
    and do not change LF child-strategy logic.
    """

    if trades.empty:
        return trades
    out = trades.copy()
    cap_after = pd.to_numeric(out.get("capital", np.nan), errors="coerce")
    pnl = pd.to_numeric(out.get("pnl", np.nan), errors="coerce")
    cap_before = (cap_after - pnl).replace(0, np.nan)
    qty = pd.to_numeric(out.get("qty", np.nan), errors="coerce").abs()
    entry = pd.to_numeric(out.get("avg_entry", out.get("first_entry", np.nan)), errors="coerce")
    first_entry = pd.to_numeric(out.get("first_entry", entry), errors="coerce")
    initial_sl = pd.to_numeric(out.get("initial_sl", np.nan), errors="coerce")
    notional = qty * entry
    out["capital_before_trade"] = cap_before
    out["position_notional"] = notional
    out["position_notional_mult"] = notional / cap_before
    out["initial_risk_amount"] = qty * (first_entry - initial_sl).abs()
    out["initial_risk_pct_equity"] = out["initial_risk_amount"] / cap_before
    out["margin_fraction_at_leverage15"] = out["position_notional_mult"] / DEFAULT_LEVERAGE
    return out


def attach_mf_position_metrics(trades: pd.DataFrame, assumed_exposure: float = 1.0) -> pd.DataFrame:
    if trades.empty:
        return trades
    out = trades.copy()
    out["position_notional_mult"] = float(assumed_exposure)
    out["initial_risk_pct_equity"] = np.nan
    out["margin_fraction_at_leverage15"] = float(assumed_exposure) / DEFAULT_LEVERAGE
    return out


def _build_mf_args(args: argparse.Namespace, out_dir: Path) -> argparse.Namespace:
    defaults = [
        "--symbol",
        args.symbol,
        "--timeframe",
        "1m",
        "--start-date",
        args.start_date,
        "--end-date",
        args.end_date,
        "--warmup-start-date",
        args.warmup_start_date,
        "--out-dir",
        str(out_dir / "_mf_child_tmp"),
        "--candidate-layers",
        "A0_fp_abs_delta_high",
        "--support-modes",
        "single_swing",
        "--entry-modes",
        "next_open",
        "--exit-modes",
        "time48,mfe_lock_15_05_time48",
        "--upgrade-stop-specs",
        "no_stop",
        "--context-sources",
        "trade_bar,footprint",
        "--micro-timeframes",
        "",
        "--micro-load-mode",
        "local",
        "--save-trades",
        "0",
        "--save-events",
        "0",
        "--initial-capital",
        str(float(args.initial_capital)),
        "--skip-full-report",
    ]
    return low_v1.parse_args(defaults)


def _make_mf_variant(variant_name: str, exit_mode: str, stop_spec: object) -> UpgradeVariant:
    return UpgradeVariant(
        variant_name=variant_name,
        candidate_layer="A0_fp_abs_delta_high",
        support_mode="single_swing",
        entry_mode="next_open",
        exit_mode=exit_mode,
        stop_spec=stop_spec,
    )


def run_low_sweep_mf_leg(args: argparse.Namespace, out_dir: Path) -> pd.DataFrame:
    """Run the frozen MF child candidates and return normalized trades."""

    mf_args = _build_mf_args(args, out_dir)
    print(f"[mf] load 1m trade bars {args.symbol} {args.warmup_start_date}->{args.end_date}", flush=True)
    bars = low_v1.load_trade_bars(mf_args)
    events = low_v1.prepare_events_and_context(bars, mf_args)
    stops = {s.name: s for s in parse_stop_specs("no_stop")}
    variants = [
        _make_mf_variant(MF_TIME48_LEG, "time48", stops["no_stop"]),
        _make_mf_variant(MF_COMFORT_LEG, "mfe_lock_15_05_time48", stops["no_stop"]),
    ]
    trades, _summary = low_v1.simulate_variant_set(bars, events, variants, mf_args, cost_mult=1.0, label="[mf] variants")
    if trades.empty:
        return pd.DataFrame()
    out = trades.copy()
    out["strategy_leg"] = out["variant_name"].map({MF_TIME48_LEG: MF_TIME48_LEG, MF_COMFORT_LEG: MF_COMFORT_LEG}).fillna("MF_LOW_SWEEP")
    out["entry_time"] = pd.to_datetime(out["entry_time"], errors="coerce")
    out["exit_time"] = pd.to_datetime(out["exit_time"], errors="coerce")
    out["side"] = 1
    out["return_on_sleeve"] = pd.to_numeric(out.get("net_return_on_equity"), errors="coerce")
    out = attach_mf_position_metrics(out, assumed_exposure=1.0)
    return out.dropna(subset=["entry_time", "exit_time", "return_on_sleeve"])


def _side_from_trade_row(row: pd.Series) -> int:
    """Return +1/-1/0 with fallback for LF trades whose side column is blank.

    Some LF V10B reports carry direction in the textual `type` column instead of
    a numeric `side` field.  Portfolio conflict/overlap diagnostics must not
    silently treat those rows as flat.
    """

    side = pd.to_numeric(row.get("side", np.nan), errors="coerce")
    if pd.notna(side) and math.isfinite(float(side)) and float(side) != 0:
        return int(np.sign(float(side)))
    typ = str(row.get("type", "")).upper()
    if "LONG" in typ:
        return 1
    if "SHORT" in typ:
        return -1
    return 0


def _active_lf_trade_at(ts: pd.Timestamp, lf_trades: pd.DataFrame) -> pd.Series | None:
    if lf_trades.empty:
        return None
    active = lf_trades.loc[(lf_trades["entry_time"] <= ts) & (lf_trades["exit_time"] > ts)]
    if active.empty:
        return None
    # V10B is single-active, but keep deterministic fallback.
    return active.sort_values("entry_time").iloc[-1]


def _lf_active_side_at(ts: pd.Timestamp, lf_trades: pd.DataFrame) -> int:
    row = _active_lf_trade_at(ts, lf_trades)
    if row is None:
        return 0
    return _side_from_trade_row(row)


def apply_conflict_filter(mf: pd.DataFrame, lf: pd.DataFrame, mode: str) -> tuple[pd.DataFrame, int]:
    if mf.empty or mode == "independent":
        return mf.copy(), 0
    keep = []
    skipped = 0
    for _, row in mf.sort_values("entry_time").iterrows():
        side = _lf_active_side_at(pd.Timestamp(row["entry_time"]), lf)
        if mode == "skip_when_lf_active" and side != 0:
            skipped += 1
            continue
        if mode == "skip_if_lf_short" and side < 0:
            skipped += 1
            continue
        keep.append(row)
    out = pd.DataFrame(keep)
    return out, int(skipped)


def _parse_guard_mode(mode: str, args: argparse.Namespace) -> tuple[str, float | None, float | None]:
    """Return normalized guard mode plus optional margin/notional caps.

    Examples:
    - none
    - margin80 / margin85
    - notional12 / notional13
    - margin85_notional13

    Caps are interpreted at MF entry using current LF active notional.  They are
    portfolio-level sizing guards only: they shrink or skip the MF sleeve and
    never reduce LF V10B.
    """

    raw = str(mode).strip().lower()
    if raw in {"", "none", "no_guard", "noguard"}:
        return "none", None, None

    margin_cap: float | None = None
    notional_cap: float | None = None
    for part in raw.split("_"):
        if part.startswith("margin"):
            suffix = part.replace("margin", "", 1)
            margin_cap = float(suffix) / 100.0 if suffix else float(args.guard_margin_cap)
        elif part.startswith("notional"):
            suffix = part.replace("notional", "", 1)
            notional_cap = float(suffix) if suffix else float(args.guard_notional_cap)
        elif part:
            raise ValueError(f"Unknown guard mode part: {part!r} in {mode!r}")

    normalized_parts: list[str] = []
    if margin_cap is not None:
        normalized_parts.append(f"margin{int(round(margin_cap * 100))}")
    if notional_cap is not None:
        normalized_parts.append(f"notional{notional_cap:g}")
    if not normalized_parts:
        return "none", None, None
    return "_".join(normalized_parts), margin_cap, notional_cap


def _scenario_name(base: str, guard_mode: str) -> str:
    if guard_mode in {"", "none"}:
        return base
    return f"{base}_guard_{guard_mode.replace('.', 'p')}"


def _lf_notional_at(ts: pd.Timestamp, lf: pd.DataFrame) -> float:
    active = _active_lf_trade_at(ts, lf)
    if active is None:
        return 0.0
    return max(0.0, _safe_float(active.get("position_notional_mult", 0.0), 0.0))


def apply_mf_sizing_guard(
    mf: pd.DataFrame,
    lf: pd.DataFrame,
    scenario: PortfolioScenario,
    *,
    leverage: float,
) -> tuple[pd.DataFrame, dict[str, object]]:
    """Apply portfolio-level sizing guard to MF trades.

    The guard models the live intent:
    - MF target notional is based on current account equity.
    - If LF is already using notional, MF is shrunk to respect total caps.
    - If the remaining allowed MF exposure is too small, MF is skipped.
    - LF trades are never reduced or closed by this function.
    """

    stats: dict[str, object] = {
        "mf_guard_scaled_count": 0,
        "mf_guard_skipped_count": 0,
        "mf_exposure_actual_avg": float("nan"),
        "mf_exposure_actual_min": float("nan"),
        "mf_exposure_actual_max": float("nan"),
        "max_combined_notional_after_mf": float("nan"),
        "max_combined_margin_after_mf": float("nan"),
    }
    if mf.empty:
        return mf.copy(), stats

    target = float(scenario.mf_exposure)
    min_exp = max(0.0, float(scenario.min_mf_exposure))
    margin_cap = scenario.margin_cap
    notional_cap = scenario.notional_cap

    kept: list[pd.Series] = []
    actuals: list[float] = []
    combined_notional_values: list[float] = []
    combined_margin_values: list[float] = []

    for _, row in mf.sort_values("entry_time").iterrows():
        ts = pd.Timestamp(row["entry_time"])
        lf_notional = _lf_notional_at(ts, lf)
        allowed = target
        if notional_cap is not None:
            allowed = min(allowed, max(0.0, float(notional_cap) - lf_notional))
        if margin_cap is not None:
            allowed = min(allowed, max(0.0, float(margin_cap) * float(leverage) - lf_notional))

        if allowed + 1e-12 < min_exp:
            stats["mf_guard_skipped_count"] = int(stats["mf_guard_skipped_count"]) + 1
            continue

        actual = max(0.0, min(target, allowed))
        if actual < target - 1e-12:
            stats["mf_guard_scaled_count"] = int(stats["mf_guard_scaled_count"]) + 1

        out = row.copy()
        out["guard_mode"] = scenario.guard_mode
        out["guard_target_mf_exposure"] = target
        out["guard_actual_mf_exposure"] = actual
        out["guard_scale"] = actual / target if target > 0 else 0.0
        out["guard_lf_notional_at_entry"] = lf_notional
        out["guard_combined_notional_after_mf"] = lf_notional + actual
        out["guard_combined_margin_after_mf"] = (lf_notional + actual) / float(leverage)
        kept.append(out)
        actuals.append(actual)
        combined_notional_values.append(lf_notional + actual)
        combined_margin_values.append((lf_notional + actual) / float(leverage))

    out_df = pd.DataFrame(kept)
    if actuals:
        stats["mf_exposure_actual_avg"] = float(np.mean(actuals))
        stats["mf_exposure_actual_min"] = float(np.min(actuals))
        stats["mf_exposure_actual_max"] = float(np.max(actuals))
        stats["max_combined_notional_after_mf"] = float(np.max(combined_notional_values))
        stats["max_combined_margin_after_mf"] = float(np.max(combined_margin_values))
    return out_df, stats


def build_scenarios(args: argparse.Namespace) -> list[PortfolioScenario]:
    scenarios: list[PortfolioScenario] = []
    guard_specs = [_parse_guard_mode(mode, args) for mode in _split_csv(args.guard_modes)]
    for exposure in _parse_float_list(args.mf_exposures):
        for mode in _split_csv(args.conflict_modes):
            if mode not in {"independent", "skip_when_lf_active", "skip_if_lf_short"}:
                raise ValueError(f"Unknown conflict mode: {mode}")
            for guard_mode, margin_cap, notional_cap in guard_specs:
                time48_base = f"portfolio_v1_lf{int(round(args.lf_weight * 100))}_mf{int(round(exposure * 100))}_time48_{mode}"
                comfort_base = f"portfolio_v1_lf{int(round(args.lf_weight * 100))}_mf{int(round(exposure * 100))}_mfe_lock_15_05_{mode}"
                scenarios.append(
                    PortfolioScenario(
                        scenario_name=_scenario_name(time48_base, guard_mode),
                        mf_variant_name=MF_TIME48_LEG,
                        mf_exposure=float(exposure),
                        conflict_mode=mode,
                        lf_weight=float(args.lf_weight),
                        guard_mode=guard_mode,
                        margin_cap=margin_cap,
                        notional_cap=notional_cap,
                        min_mf_exposure=float(args.min_mf_exposure),
                    )
                )
                scenarios.append(
                    PortfolioScenario(
                        scenario_name=_scenario_name(comfort_base, guard_mode),
                        mf_variant_name=MF_COMFORT_LEG,
                        mf_exposure=float(exposure),
                        conflict_mode=mode,
                        lf_weight=float(args.lf_weight),
                        guard_mode=guard_mode,
                        margin_cap=margin_cap,
                        notional_cap=notional_cap,
                        min_mf_exposure=float(args.min_mf_exposure),
                    )
                )
    return scenarios


def _profit_factor(returns: pd.Series) -> float:
    ret = pd.to_numeric(returns, errors="coerce").dropna()
    gains = float(ret[ret > 0].sum())
    losses = float(-ret[ret < 0].sum())
    if losses <= 0:
        return float("inf") if gains > 0 else float("nan")
    return gains / losses


def _max_drawdown(capital: pd.Series) -> float:
    if capital.empty:
        return float("nan")
    peak = capital.cummax()
    dd = capital / peak - 1.0
    return float(dd.min())


def simulate_portfolio_scenario(
    lf: pd.DataFrame,
    mf_all: pd.DataFrame,
    scenario: PortfolioScenario,
    *,
    initial_capital: float,
    leverage: float = DEFAULT_LEVERAGE,
) -> tuple[pd.DataFrame, dict[str, object]]:
    lf_part = lf.copy()
    lf_part["scenario"] = scenario.scenario_name
    lf_part["portfolio_return"] = pd.to_numeric(lf_part["return_on_sleeve"], errors="coerce") * float(scenario.lf_weight)
    lf_part["portfolio_weight"] = float(scenario.lf_weight)
    lf_part["position_scope"] = "lf_v10b_sleeve"
    lf_part["close_scope"] = "lf_v10b_only"
    lf_part["scenario_notional_exposure"] = pd.to_numeric(lf_part.get("position_notional_mult", np.nan), errors="coerce") * float(scenario.lf_weight)

    mf_raw = mf_all.loc[mf_all["variant_name"].eq(scenario.mf_variant_name)].copy()
    mf_part, skipped = apply_conflict_filter(mf_raw, lf, scenario.conflict_mode)
    mf_part, guard_stats = apply_mf_sizing_guard(mf_part, lf, scenario, leverage=float(leverage))
    if not mf_part.empty:
        actual_exp = pd.to_numeric(mf_part.get("guard_actual_mf_exposure", scenario.mf_exposure), errors="coerce").fillna(float(scenario.mf_exposure))
        mf_part["scenario"] = scenario.scenario_name
        mf_part["portfolio_return"] = pd.to_numeric(mf_part["return_on_sleeve"], errors="coerce") * actual_exp
        mf_part["portfolio_weight"] = actual_exp
        mf_part["position_scope"] = "mf_low_sweep_sleeve"
        mf_part["close_scope"] = "mf_low_sweep_only"
        mf_part["scenario_notional_exposure"] = actual_exp

    combined = pd.concat([lf_part, mf_part], ignore_index=True, sort=False)
    if combined.empty:
        return combined, {
            "scenario": scenario.scenario_name,
            "total_trades": 0,
            "return_total": 0.0,
            "max_drawdown": 0.0,
            "mf_skipped_by_conflict": int(skipped),
            "guard_mode": scenario.guard_mode,
            "margin_cap": scenario.margin_cap,
            "notional_cap": scenario.notional_cap,
            **guard_stats,
        }
    combined["exit_time"] = pd.to_datetime(combined["exit_time"], errors="coerce")
    combined["entry_time"] = pd.to_datetime(combined["entry_time"], errors="coerce")
    combined = combined.dropna(subset=["entry_time", "exit_time", "portfolio_return"]).sort_values(["exit_time", "strategy_leg", "entry_time"]).reset_index(drop=True)

    capital = float(initial_capital)
    caps = []
    pnls = []
    for _, row in combined.iterrows():
        ret = float(row["portfolio_return"])
        pnl = capital * ret
        capital += pnl
        pnls.append(pnl)
        caps.append(capital)
    combined["portfolio_pnl"] = pnls
    combined["portfolio_capital"] = caps

    ret = pd.to_numeric(combined["portfolio_return"], errors="coerce")
    summary = {
        "scenario": scenario.scenario_name,
        "lf_weight": float(scenario.lf_weight),
        "mf_variant_name": scenario.mf_variant_name,
        "mf_exposure": float(scenario.mf_exposure),
        "mf_margin_fraction_at_15x": float(scenario.mf_exposure) / DEFAULT_LEVERAGE,
        "conflict_mode": scenario.conflict_mode,
        "guard_mode": scenario.guard_mode,
        "margin_cap": scenario.margin_cap,
        "notional_cap": scenario.notional_cap,
        "min_mf_exposure": float(scenario.min_mf_exposure),
        "total_trades": int(len(combined)),
        "lf_trades": int(combined["strategy_leg"].eq(LF_LEG).sum()),
        "mf_trades": int(combined["strategy_leg"].isin([MF_TIME48_LEG, MF_COMFORT_LEG]).sum()),
        "mf_skipped_by_conflict": int(skipped),
        **guard_stats,
        "return_total": float(capital / float(initial_capital) - 1.0),
        "final_capital": float(capital),
        "win_rate": float((ret > 0).mean()) if len(ret) else float("nan"),
        "profit_factor": _profit_factor(ret),
        "max_drawdown": _max_drawdown(pd.Series(caps, dtype=float)),
        "avg_trade_return": float(ret.mean()) if len(ret) else float("nan"),
        "median_trade_return": float(ret.median()) if len(ret) else float("nan"),
        "worst_trade_return": float(ret.min()) if len(ret) else float("nan"),
        "best_trade_return": float(ret.max()) if len(ret) else float("nan"),
        "first_entry_time": combined["entry_time"].min(),
        "last_exit_time": combined["exit_time"].max(),
    }
    return combined, summary


def summarize_period(combined: pd.DataFrame, period: str) -> pd.DataFrame:
    if combined.empty:
        return pd.DataFrame()
    df = combined.copy()
    df["exit_time"] = pd.to_datetime(df["exit_time"], errors="coerce")
    if period == "year":
        df["period"] = df["exit_time"].dt.year.astype(str)
    elif period == "month":
        df["period"] = df["exit_time"].dt.to_period("M").astype(str)
    else:
        raise ValueError(period)
    rows: list[dict[str, object]] = []
    for (scenario, per), grp in df.groupby(["scenario", "period"], dropna=False):
        r = pd.to_numeric(grp["portfolio_return"], errors="coerce").dropna()
        rows.append(
            {
                "scenario": scenario,
                "period": per,
                "trades": int(len(grp)),
                "lf_trades": int(grp["strategy_leg"].eq(LF_LEG).sum()),
                "mf_trades": int(grp["strategy_leg"].isin([MF_TIME48_LEG, MF_COMFORT_LEG]).sum()),
                "period_return_compounded": float(np.prod(1.0 + r.to_numpy(dtype=float)) - 1.0) if len(r) else 0.0,
                "win_rate": float((r > 0).mean()) if len(r) else float("nan"),
                "profit_factor": _profit_factor(r),
                "worst_trade_return": float(r.min()) if len(r) else float("nan"),
            }
        )
    return pd.DataFrame(rows).sort_values(["scenario", "period"]).reset_index(drop=True)


def build_overlap_report(lf: pd.DataFrame, mf: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for name, grp in mf.groupby("variant_name", dropna=False):
        active = 0
        active_short = 0
        active_long = 0
        for _, row in grp.iterrows():
            side = _lf_active_side_at(pd.Timestamp(row["entry_time"]), lf)
            if side != 0:
                active += 1
            if side < 0:
                active_short += 1
            if side > 0:
                active_long += 1
        rows.append(
            {
                "mf_variant_name": name,
                "mf_trades": int(len(grp)),
                "lf_active_at_mf_entry": int(active),
                "lf_long_at_mf_entry": int(active_long),
                "lf_short_at_mf_entry": int(active_short),
                "lf_active_ratio": float(active / len(grp)) if len(grp) else float("nan"),
                "lf_short_ratio": float(active_short / len(grp)) if len(grp) else float("nan"),
            }
        )
    return pd.DataFrame(rows)


def _series_stat(series: pd.Series, fn: str) -> float:
    s = pd.to_numeric(series, errors="coerce").dropna()
    if s.empty:
        return float("nan")
    if fn == "median":
        return float(s.median())
    if fn == "p75":
        return float(s.quantile(0.75))
    if fn == "p95":
        return float(s.quantile(0.95))
    if fn == "max":
        return float(s.max())
    if fn == "mean":
        return float(s.mean())
    raise ValueError(fn)


def build_margin_overlap_stress(lf: pd.DataFrame, mf: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    """Summarize independent-sleeve margin/exposure at MF entry times.

    This is a diagnostic, not a conflict filter.  MF Low Sweep is allowed to run
    independently, but the report shows whether a new MF sleeve can reasonably
    add its fixed notional exposure while LF V10B is already active.
    """

    leverage = float(getattr(args, "leverage", DEFAULT_LEVERAGE) or DEFAULT_LEVERAGE)
    exposures = _parse_float_list(args.mf_exposures)
    rows: list[dict[str, object]] = []
    if mf.empty:
        return pd.DataFrame(rows)
    variants = [MF_TIME48_LEG, MF_COMFORT_LEG]
    for variant in variants:
        mfv = mf.loc[mf["variant_name"].eq(variant)].copy()
        if mfv.empty:
            continue
        active_records: list[dict[str, object]] = []
        for _, row in mfv.sort_values("entry_time").iterrows():
            ts = pd.Timestamp(row["entry_time"])
            active = _active_lf_trade_at(ts, lf)
            lf_side = 0
            lf_notional = 0.0
            lf_engine = "NONE"
            if active is not None:
                lf_side = _side_from_trade_row(active)
                lf_notional = float(pd.to_numeric(active.get("position_notional_mult", 0.0), errors="coerce") or 0.0)
                lf_engine = str(active.get("engine", "UNKNOWN"))
            active_records.append({"lf_side": lf_side, "lf_notional": lf_notional, "lf_engine": lf_engine})
        active_df = pd.DataFrame(active_records)
        lf_notional_series = pd.to_numeric(active_df.get("lf_notional", pd.Series(dtype=float)), errors="coerce").fillna(0.0)
        lf_active = lf_notional_series > 0
        for exp in exposures:
            total_notional = lf_notional_series + float(exp)
            total_margin = total_notional / leverage
            rows.append(
                {
                    "mf_variant_name": variant,
                    "mf_exposure": float(exp),
                    "mf_margin_fraction_at_leverage": float(exp) / leverage,
                    "mf_trades": int(len(mfv)),
                    "lf_active_at_mf_entry": int(lf_active.sum()),
                    "lf_long_at_mf_entry": int((active_df.get("lf_side", pd.Series(dtype=int)) > 0).sum()),
                    "lf_short_at_mf_entry": int((active_df.get("lf_side", pd.Series(dtype=int)) < 0).sum()),
                    "lf_active_ratio": float(lf_active.mean()) if len(lf_active) else float("nan"),
                    "lf_notional_at_mf_entry_median": _series_stat(lf_notional_series, "median"),
                    "lf_notional_at_mf_entry_p75": _series_stat(lf_notional_series, "p75"),
                    "lf_notional_at_mf_entry_p95": _series_stat(lf_notional_series, "p95"),
                    "lf_notional_at_mf_entry_max": _series_stat(lf_notional_series, "max"),
                    "combined_notional_at_mf_entry_median": _series_stat(total_notional, "median"),
                    "combined_notional_at_mf_entry_p75": _series_stat(total_notional, "p75"),
                    "combined_notional_at_mf_entry_p95": _series_stat(total_notional, "p95"),
                    "combined_notional_at_mf_entry_max": _series_stat(total_notional, "max"),
                    "combined_margin_fraction_p95": _series_stat(total_margin, "p95"),
                    "combined_margin_fraction_max": _series_stat(total_margin, "max"),
                    "combined_margin_over_80pct_count": int((total_margin > 0.80).sum()),
                    "combined_margin_over_90pct_count": int((total_margin > 0.90).sum()),
                    "combined_margin_over_100pct_count": int((total_margin > 1.00).sum()),
                    "sizing_note": "MF fixed exposure is an independent sleeve; live sizing should use account equity at MF entry with a total-exposure/margin guard, not reduce LF positions.",
                }
            )
    return pd.DataFrame(rows)


def _classify_lf_state(side: int) -> str:
    if side > 0:
        return "LF_LONG"
    if side < 0:
        return "LF_SHORT"
    return "LF_NONE"


def build_mf_by_lf_state_report(lf: pd.DataFrame, mf: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    """Break down MF Low Sweep results by LF state at MF entry.

    This diagnostic keeps the portfolio mode independent.  It does not filter
    or resize trades; it answers whether MF performs better when LF V10B is
    flat, long, or short at the MF entry timestamp.
    """

    leverage = float(getattr(args, "leverage", DEFAULT_LEVERAGE) or DEFAULT_LEVERAGE)
    exposures = _parse_float_list(args.mf_exposures)
    rows: list[dict[str, object]] = []
    if mf.empty:
        return pd.DataFrame(rows)

    variants = [MF_TIME48_LEG, MF_COMFORT_LEG]
    for variant in variants:
        mfv = mf.loc[mf["variant_name"].eq(variant)].copy()
        if mfv.empty:
            continue
        records: list[dict[str, object]] = []
        for _, row in mfv.sort_values("entry_time").iterrows():
            ts = pd.Timestamp(row["entry_time"])
            active = _active_lf_trade_at(ts, lf)
            lf_side = 0
            lf_notional = 0.0
            lf_engine = "NONE"
            if active is not None:
                lf_side = _side_from_trade_row(active)
                lf_notional = _safe_float(active.get("position_notional_mult", 0.0), 0.0)
                lf_engine = str(active.get("engine", "UNKNOWN"))
            ret = _safe_float(row.get("return_on_sleeve", np.nan), float("nan"))
            records.append(
                {
                    "entry_time": ts,
                    "exit_time": pd.Timestamp(row["exit_time"]),
                    "lf_state_at_mf_entry": _classify_lf_state(lf_side),
                    "lf_side_at_mf_entry": int(lf_side),
                    "lf_engine_at_mf_entry": lf_engine,
                    "lf_notional_at_mf_entry": float(lf_notional),
                    "mf_return_1x": ret,
                }
            )
        detail = pd.DataFrame(records)
        if detail.empty:
            continue
        all_states = ["LF_NONE", "LF_LONG", "LF_SHORT"]
        for state in all_states:
            grp = detail.loc[detail["lf_state_at_mf_entry"].eq(state)].copy()
            if grp.empty:
                continue
            raw_ret = pd.to_numeric(grp["mf_return_1x"], errors="coerce").dropna()
            lf_notional = pd.to_numeric(grp["lf_notional_at_mf_entry"], errors="coerce").fillna(0.0)
            common: dict[str, object] = {
                "mf_variant_name": variant,
                "lf_state_at_mf_entry": state,
                "mf_trades": int(len(grp)),
                "first_mf_entry_time": grp["entry_time"].min(),
                "last_mf_exit_time": grp["exit_time"].max(),
                "mf_return_1x_compounded": float(np.prod(1.0 + raw_ret.to_numpy(dtype=float)) - 1.0) if len(raw_ret) else 0.0,
                "mf_win_rate": float((raw_ret > 0).mean()) if len(raw_ret) else float("nan"),
                "mf_profit_factor_1x": _profit_factor(raw_ret),
                "mf_avg_return_1x": float(raw_ret.mean()) if len(raw_ret) else float("nan"),
                "mf_median_return_1x": float(raw_ret.median()) if len(raw_ret) else float("nan"),
                "mf_worst_return_1x": float(raw_ret.min()) if len(raw_ret) else float("nan"),
                "mf_best_return_1x": float(raw_ret.max()) if len(raw_ret) else float("nan"),
                "lf_notional_at_mf_entry_median": _series_stat(lf_notional, "median"),
                "lf_notional_at_mf_entry_p75": _series_stat(lf_notional, "p75"),
                "lf_notional_at_mf_entry_max": _series_stat(lf_notional, "max"),
                "sizing_base_note": "MF live sizing should use current account equity at MF entry; this report only groups historical MF returns by LF state.",
            }
            engine_counts = grp["lf_engine_at_mf_entry"].value_counts(dropna=False).to_dict()
            common["lf_engine_counts"] = json.dumps(engine_counts, ensure_ascii=False)
            for exp in exposures:
                scaled = raw_ret * float(exp)
                total_notional = lf_notional + float(exp)
                total_margin = total_notional / leverage
                row = dict(common)
                row.update(
                    {
                        "mf_exposure": float(exp),
                        "mf_margin_fraction_at_leverage": float(exp) / leverage,
                        "mf_return_at_exposure_compounded": float(np.prod(1.0 + scaled.to_numpy(dtype=float)) - 1.0) if len(scaled) else 0.0,
                        "mf_profit_factor_at_exposure": _profit_factor(scaled),
                        "mf_worst_return_at_exposure": float(scaled.min()) if len(scaled) else float("nan"),
                        "combined_notional_at_mf_entry_median": _series_stat(total_notional, "median"),
                        "combined_notional_at_mf_entry_p75": _series_stat(total_notional, "p75"),
                        "combined_notional_at_mf_entry_max": _series_stat(total_notional, "max"),
                        "combined_margin_fraction_max": _series_stat(total_margin, "max"),
                    }
                )
                rows.append(row)
    if not rows:
        return pd.DataFrame(rows)
    order = {"LF_NONE": 0, "LF_LONG": 1, "LF_SHORT": 2}
    out = pd.DataFrame(rows)
    out["_state_order"] = out["lf_state_at_mf_entry"].map(order).fillna(99)
    out = out.sort_values(["mf_variant_name", "mf_exposure", "_state_order"]).drop(columns=["_state_order"]).reset_index(drop=True)
    return out



def build_guard_summary(summary: pd.DataFrame) -> pd.DataFrame:
    """Compact guard comparison table derived from scenario summary."""

    if summary.empty:
        return pd.DataFrame()
    preferred = [
        "scenario",
        "mf_variant_name",
        "mf_exposure",
        "conflict_mode",
        "guard_mode",
        "margin_cap",
        "notional_cap",
        "min_mf_exposure",
        "total_trades",
        "lf_trades",
        "mf_trades",
        "mf_skipped_by_conflict",
        "mf_guard_scaled_count",
        "mf_guard_skipped_count",
        "mf_exposure_actual_avg",
        "mf_exposure_actual_min",
        "mf_exposure_actual_max",
        "max_combined_notional_after_mf",
        "max_combined_margin_after_mf",
        "return_total",
        "final_capital",
        "win_rate",
        "profit_factor",
        "max_drawdown",
        "worst_trade_return",
    ]
    cols = [c for c in preferred if c in summary.columns]
    return summary.loc[:, cols].copy()

def build_sizing_report(lf: pd.DataFrame, mf: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    """Summarize LF risk-budget sizing and MF fixed exposure assumptions."""

    leverage = float(getattr(args, "leverage", DEFAULT_LEVERAGE) or DEFAULT_LEVERAGE)
    exposures = _parse_float_list(args.mf_exposures)
    rows: list[dict[str, object]] = []

    # Config-level sizing: these are caps/risk-budget inputs, not realized exposure.
    mom = v10a.MOMENTUM_PRESETS[str(args.lf_preset)]
    bear = v10a.BEAR_PRESETS[str(args.lf_bear_preset)]
    bull = v10a.BULL_PRESETS[str(args.lf_bull_preset)]
    for engine, preset, min_mult in [
        ("MOMENTUM_V3", mom, 0.35),
        ("BEAR_V3_ONLY", bear, 0.25),
        ("BULL_RECLAIM_V2", bull, 0.35),
    ]:
        rows.append(
            {
                "section": "lf_config_cap",
                "leg": LF_LEG,
                "engine": engine,
                "preset": str(args.lf_preset if engine == "MOMENTUM_V3" else args.lf_bear_preset if engine == "BEAR_V3_ONLY" else args.lf_bull_preset),
                "unit_risk_per_trade": float(preset["unit_risk_per_trade"]),
                "max_total_notional_mult": float(preset["max_total_notional_mult"]),
                "max_units": int(preset["max_units"]),
                "min_risk_mult": float(min_mult),
                "max_risk_mult": float(preset["max_risk_mult"]),
                "global_risk_scale": float(args.lf_global_risk_scale),
                "max_initial_risk_pct_before_quality_micro": float(preset["unit_risk_per_trade"]) * float(preset["max_risk_mult"]),
                "leverage_for_margin_report": leverage,
            }
        )

    if not lf.empty:
        lf2 = lf.copy()
        if "engine" not in lf2.columns:
            lf2["engine"] = "UNKNOWN"
        for engine, grp in lf2.groupby("engine", dropna=False):
            rows.append(
                {
                    "section": "lf_actual_closed_trades",
                    "leg": LF_LEG,
                    "engine": engine,
                    "trades": int(len(grp)),
                    "notional_mult_median": _series_stat(grp.get("position_notional_mult", pd.Series(dtype=float)), "median"),
                    "notional_mult_p75": _series_stat(grp.get("position_notional_mult", pd.Series(dtype=float)), "p75"),
                    "notional_mult_p95": _series_stat(grp.get("position_notional_mult", pd.Series(dtype=float)), "p95"),
                    "notional_mult_max": _series_stat(grp.get("position_notional_mult", pd.Series(dtype=float)), "max"),
                    "initial_risk_pct_median": _series_stat(grp.get("initial_risk_pct_equity", pd.Series(dtype=float)), "median"),
                    "initial_risk_pct_p95": _series_stat(grp.get("initial_risk_pct_equity", pd.Series(dtype=float)), "p95"),
                    "units_median": _series_stat(grp.get("units", pd.Series(dtype=float)), "median"),
                    "units_max": _series_stat(grp.get("units", pd.Series(dtype=float)), "max"),
                    "margin_fraction_p95_at_leverage": _series_stat(grp.get("position_notional_mult", pd.Series(dtype=float)), "p95") / leverage,
                    "margin_fraction_max_at_leverage": _series_stat(grp.get("position_notional_mult", pd.Series(dtype=float)), "max") / leverage,
                }
            )

    for exp in exposures:
        rows.append(
            {
                "section": "mf_assumed_fixed_exposure",
                "leg": "MF_LOW_SWEEP",
                "engine": "A0_FOOTPRINT",
                "trades_time48": int(mf["variant_name"].eq(MF_TIME48_LEG).sum()) if not mf.empty else 0,
                "trades_comfort": int(mf["variant_name"].eq(MF_COMFORT_LEG).sum()) if not mf.empty else 0,
                "notional_mult_fixed": float(exp),
                "margin_fraction_at_leverage": float(exp) / leverage,
                "leverage_for_margin_report": leverage,
                "close_scope": "mf_low_sweep_only",
            }
        )
    return pd.DataFrame(rows)


def build_report_trades(combined: pd.DataFrame, initial_capital: float) -> tuple[list[dict[str, object]], float]:
    if combined.empty:
        return [], float(initial_capital)
    out: list[dict[str, object]] = []
    capital = float(initial_capital)
    for _, row in combined.sort_values(["exit_time", "strategy_leg", "entry_time"]).iterrows():
        ret = float(row["portfolio_return"])
        pnl = capital * ret
        capital += pnl
        side = _safe_side_from_row(row, default=1)
        fee = _safe_float(row.get("fee", row.get("total_entry_fee", 0.0)), 0.0)
        if not math.isfinite(fee):
            fee = 0.0
        out.append(
            {
                "entry_time": pd.Timestamp(row["entry_time"]),
                "exit_time": pd.Timestamp(row["exit_time"]),
                "type": "LONG" if side >= 0 else "SHORT",
                "entry": float(row.get("entry_price", row.get("entry", np.nan))),
                "exit": float(row.get("exit_price", row.get("exit", np.nan))),
                "pnl": float(pnl),
                "fee": float(fee),
                "capital": float(capital),
                "mfe_r": float(row.get("mfe_on_equity", row.get("mfe_r", np.nan))),
                "mae_r": float(row.get("mae_on_equity", row.get("mae_r", np.nan))),
                "exit_reason": f"{row.get('strategy_leg')}:{row.get('exit_reason', row.get('note', ''))}",
            }
        )
    return out, capital


def print_scenario_full_report(primary: pd.DataFrame, args: argparse.Namespace, out_dir: Path) -> None:
    if bool(args.skip_full_report) or primary.empty:
        return
    # Use the existing 4H loader only as a report calendar/price frame.  The
    # report helper mainly needs timestamps and OHLC for output consistency.
    df = v10a.load_data(args.symbol, args.start_date, args.end_date, "4H")
    if len(df):
        primary_end = pd.to_datetime(primary["exit_time"], errors="coerce").max()
        primary_start = pd.to_datetime(primary["entry_time"], errors="coerce").min()
        if pd.notna(primary_end) and primary_end > df.index[-1]:
            # Local 4H cache may end before MF 1m trades.  Append a synthetic
            # calendar row so the full report title/duration covers all trades.
            last = df.iloc[-1:].copy()
            last.index = pd.DatetimeIndex([primary_end])
            df = pd.concat([df, last]).sort_index()
        if pd.notna(primary_start) and primary_start < df.index[0]:
            first = df.iloc[:1].copy()
            first.index = pd.DatetimeIndex([primary_start])
            df = pd.concat([first, df]).sort_index()
    total_days = max((df.index[-1] - df.index[0]).total_seconds() / 86400.0, 1e-9) if len(df) else 1e-9
    report_trades, final_capital = build_report_trades(primary, float(args.initial_capital))
    print("[report] print_full_report primary portfolio scenario", flush=True)
    print_full_report(
        trade_history=report_trades,
        df=df,
        initial_capital=float(args.initial_capital),
        capital=float(final_capital),
        strategy_name=REPORT_STRATEGY_NAME,
        total_days=total_days,
        ai_enabled=False,
        symbol=args.symbol,
        report_dir=out_dir,
    )


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    # Older patch versions wrote meta to 08_meta.json.  The stable file name is
    # now 09_meta.json because 08 is reserved for sleeve sizing diagnostics.
    stale_meta = out_dir / "08_meta.json"
    if stale_meta.exists():
        stale_meta.unlink()

    print(f"[run] {SCRIPT_NAME}", flush=True)
    print(f"[args] out_dir={out_dir}", flush=True)
    print("[scope] portfolio-layer backtest only; child strategy logic is frozen", flush=True)

    lf_trades, lf_equity = run_lf_v10b_leg(args)
    mf_trades = run_low_sweep_mf_leg(args, out_dir)
    scenarios = build_scenarios(args)

    all_trades: list[pd.DataFrame] = []
    summary_rows: list[dict[str, object]] = []
    primary_trades = pd.DataFrame()
    for scenario in scenarios:
        combined, summary = simulate_portfolio_scenario(
            lf_trades,
            mf_trades,
            scenario,
            initial_capital=float(args.initial_capital),
            leverage=float(args.leverage),
        )
        all_trades.append(combined)
        summary_rows.append(summary)
        if scenario.scenario_name == args.primary_scenario:
            primary_trades = combined.copy()

    combined_all = pd.concat(all_trades, ignore_index=True, sort=False) if all_trades else pd.DataFrame()
    summary = pd.DataFrame(summary_rows).sort_values(["mf_variant_name", "mf_exposure", "conflict_mode", "guard_mode"]).reset_index(drop=True)
    yearly = summarize_period(combined_all, "year")
    monthly = summarize_period(combined_all, "month")
    overlap = build_overlap_report(lf_trades, mf_trades)
    sizing = build_sizing_report(lf_trades, mf_trades, args)
    margin_stress = build_margin_overlap_stress(lf_trades, mf_trades, args)
    mf_by_lf_state = build_mf_by_lf_state_report(lf_trades, mf_trades, args)
    guard_summary = build_guard_summary(summary)

    if int(args.save_combined_trades) >= 0 and not combined_all.empty:
        trades_out = combined_all.head(int(args.save_combined_trades)).copy()
    else:
        trades_out = pd.DataFrame()

    write_csv(lf_trades, out_dir / "01_lf_v10b_trades.csv", "lf_trades")
    write_csv(mf_trades, out_dir / "02_mf_low_sweep_trades.csv", "mf_trades")
    write_csv(trades_out, out_dir / "03_combined_trades.csv", "combined_trades")
    write_csv(summary, out_dir / "04_scenario_summary.csv", "scenario_summary")
    write_csv(yearly, out_dir / "05_yearly.csv", "yearly")
    write_csv(monthly, out_dir / "06_monthly.csv", "monthly")
    write_csv(overlap, out_dir / "07_lf_mf_overlap.csv", "overlap")
    write_csv(sizing, out_dir / "08_sleeve_sizing.csv", "sleeve_sizing")
    write_csv(margin_stress, out_dir / "10_margin_overlap_stress.csv", "margin_overlap_stress")
    write_csv(mf_by_lf_state, out_dir / "11_mf_by_lf_state.csv", "mf_by_lf_state")
    write_csv(guard_summary, out_dir / "12_guard_summary.csv", "guard_summary")

    meta = {
        "script": SCRIPT_NAME,
        "class": "portfolio_overlay_backtest",
        "live_trading": False,
        "symbol": args.symbol,
        "start_date": args.start_date,
        "end_date": args.end_date,
        "warmup_start_date": args.warmup_start_date,
        "initial_capital": float(args.initial_capital),
        "lf_leg": "backtest/lf/eth_lf_portfolio_v10b_all_swing_structural_stop_backtest.py",
        "mf_leg": "backtest/mf/low_sweep/low_sweep_V1_a0_footprint_backtest.py",
        "mf_main_variant": "A0_fp_abs_delta_high + single_swing + next_open + time48",
        "mf_comfort_variant": "A0_fp_abs_delta_high + single_swing + next_open + mfe_lock_15_05_time48",
        "primary_scenario": args.primary_scenario,
        "lf_weight": float(args.lf_weight),
        "mf_exposures": _parse_float_list(args.mf_exposures),
        "default_leverage_for_margin_report": float(args.leverage),
        "conflict_modes": _split_csv(args.conflict_modes),
        "guard_modes": _split_csv(args.guard_modes),
        "guard_margin_cap": float(args.guard_margin_cap),
        "guard_notional_cap": float(args.guard_notional_cap),
        "min_mf_exposure": float(args.min_mf_exposure),
        "return_model": "closed-trade event-level compounding; MF portfolio_return = MF 1x net return * actual_guarded_mf_exposure; LF portfolio_return = LF sleeve return * lf_weight",
        "live_sizing_recommendation": "For independent mode, size MF from current account equity at MF entry and keep MF close_scope=mf_low_sweep_only; portfolio guards may shrink/skip MF but must never force-close LF V10B.",
        "limitations": [
            "does not mark open LF/MF positions intrabar",
            "does not alter child strategy signal/entry/exit/stop logic",
            "not a live-trading strategy",
            "MF close events are modeled as closing only the MF low-sweep sleeve, not LF V10B positions",
        ],
        "causal_guards": [
            "child strategies generate trades with their existing causal backtest pipelines",
            "portfolio layer only consumes completed child trades",
            "conflict filters use MF entry_time against already simulated LF intervals",
        ],
        "outputs": [
            "01_lf_v10b_trades.csv",
            "02_mf_low_sweep_trades.csv",
            "03_combined_trades.csv",
            "04_scenario_summary.csv",
            "05_yearly.csv",
            "06_monthly.csv",
            "07_lf_mf_overlap.csv",
            "08_sleeve_sizing.csv",
            "10_margin_overlap_stress.csv",
            "11_mf_by_lf_state.csv",
            "12_guard_summary.csv",
            "09_meta.json",
        ],
    }
    (out_dir / "09_meta.json").write_text(json.dumps(meta, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
    print(f"[write] meta -> {out_dir / '09_meta.json'}", flush=True)
    print_scenario_full_report(primary_trades, args, out_dir)
    print("[done] ETH portfolio V1 overlay backtest complete", flush=True)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
