#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""End-to-end R03.4 state-context opening-value ablation."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

from src.ai_research.market_state_continuity.config import DEFAULT_MARKET_STATE_CONTINUITY_CONFIG
from src.ai_research.market_state_continuity.data import UnifiedOHLCVLoader, run_state_data_preflight
from src.ai_research.market_state_continuity.state_cache import build_state_caches
from src.ai_research.swing_baseline.dataset import (
    create_loader,
    list_cached_years,
    run_public_loader_preflight,
)
from src.ai_research.swing_long_context.config import LONG_CONTEXT_BASE_CONFIG
from src.research_common.progress import ProgressReporter

from .config import (
    DEFAULT_STATE_CONTEXT_ABLATION_CONFIG,
    STAGE_ID,
    STAGE_NAME,
    StateContextAblationConfig,
)
from .modeling import (
    activity_persistence_feature,
    build_uplift_table,
    collect_ablation_period_data,
    default_ablation_folds,
    evaluate_opening_value_model,
    fit_opening_value_model,
    select_stable_uplift,
)
from .outcomes import build_outcome_caches, load_outcome_year_shard
from .reports import write_reports


@dataclass(frozen=True)
class StateContextAblationResult:
    decision: str
    report_dir: Path
    champion: dict[str, object] | None


def _causal_audit(config: StateContextAblationConfig) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "check": "base_feature_availability",
                "status": "PASS",
                "detail": "all multiframe features come from completed bars on the existing R03.2 causal decision axis",
            },
            {
                "check": "state_feature_availability",
                "status": "PASS",
                "detail": "strategic/tactical/entry/activity state, age, boundary margin and alignment use only current and past bars",
            },
            {
                "check": "activity_probability_nested_training",
                "status": "PASS",
                "detail": "fit/calibration/test activity-persistence probabilities are generated by models trained only before each prediction period",
            },
            {
                "check": "entry_timing",
                "status": "PASS",
                "detail": "entry price is the existing next-minute open after each 15-minute decision",
            },
            {
                "check": "future_outcome_isolation",
                "status": "PASS",
                "detail": "future MFE, MAE and close return are labels/evaluation outcomes only and never enter model features",
            },
            {
                "check": "sealed_holdout",
                "status": "PASS",
                "detail": "2026 is not loaded into training, calibration, test, threshold selection or model selection",
            },
        ]
    )


def _target_distribution(outcome_paths: list[Path], config: StateContextAblationConfig) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for path in outcome_paths:
        shard = load_outcome_year_shard(path)
        for name in config.outcome_columns():
            values = np.asarray(shard.outcomes[:, shard.outcome_index[name]], dtype=float)
            values = values[np.isfinite(values)]
            if not len(values):
                continue
            rows.append(
                {
                    "year": shard.year,
                    "outcome": name,
                    "rows": int(len(values)),
                    "mean": float(np.mean(values)),
                    "median": float(np.median(values)),
                    "q10": float(np.quantile(values, 0.10)),
                    "q90": float(np.quantile(values, 0.90)),
                }
            )
    return pd.DataFrame(rows)


def _importance(model, columns: tuple[str, ...], fold_id: str, variant: str) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for side, raw in (("long", model.long_model), ("short", model.short_model)):
        values = getattr(raw, "feature_importances_", None)
        if values is None:
            continue
        rows.extend(
            {
                "fold_id": fold_id,
                "variant": variant,
                "side": side,
                "feature": column,
                "importance": float(value),
            }
            for column, value in zip(columns, values, strict=True)
        )
    return rows


def _attach_activity_probabilities(
    fold,
    fit,
    calibration,
    test,
    state_paths: list[Path],
    trade_paths: list[Path],
):
    embargo = pd.Timedelta(hours=4)
    fit_probability = activity_persistence_feature(
        state_paths,
        trade_paths,
        prediction_times_ns=fit.timestamps_ns,
        train_start=pd.Timestamp("2021-01-01"),
        train_end=fold.fit_start - embargo,
        prediction_start=fold.fit_start,
        prediction_end=fold.fit_end,
    )
    calibration_probability = activity_persistence_feature(
        state_paths,
        trade_paths,
        prediction_times_ns=calibration.timestamps_ns,
        train_start=pd.Timestamp("2021-01-01"),
        train_end=fold.fit_end,
        prediction_start=fold.calibration_start,
        prediction_end=fold.calibration_end,
    )
    test_probability = activity_persistence_feature(
        state_paths,
        trade_paths,
        prediction_times_ns=test.timestamps_ns,
        train_start=pd.Timestamp("2021-01-01"),
        train_end=fold.calibration_end - embargo,
        prediction_start=fold.test_start,
        prediction_end=fold.test_end,
    )
    return (
        fit.with_activity_probability(fit_probability),
        calibration.with_activity_probability(calibration_probability),
        test.with_activity_probability(test_probability),
    )


def run_state_context_ablation(
    *,
    data_dir: str | Path | None = None,
    force_rebuild_state_cache: bool = False,
    force_rebuild_outcomes: bool = False,
    progress: bool = True,
    config: StateContextAblationConfig = DEFAULT_STATE_CONTEXT_ABLATION_CONFIG,
) -> StateContextAblationResult:
    config.validate()
    base_loader = create_loader(LONG_CONTEXT_BASE_CONFIG, data_dir=data_dir)
    base_preflight = run_public_loader_preflight(
        base_loader,
        LONG_CONTEXT_BASE_CONFIG,
        sample_dates=("2023-06-15", "2024-06-15", "2025-06-15"),
    )
    state_loader = UnifiedOHLCVLoader(DEFAULT_MARKET_STATE_CONTINUITY_CONFIG, data_dir=data_dir)
    state_preflight = run_state_data_preflight(state_loader, DEFAULT_MARKET_STATE_CONTINUITY_CONFIG)
    preflight = {"trade_bar": base_preflight.to_dict(), "unified_state_ohlcv": state_preflight.to_dict()}
    if base_preflight.status != "PASS" or state_preflight.status != "PASS":
        decision = "BLOCKED_DATA"
        reason = "Trade Bar或统一状态OHLCV预检失败。"
        write_reports(
            config.report_path,
            manifest={"stage": STAGE_ID, "name": STAGE_NAME, "config": config.to_dict()},
            preflight=preflight,
            target_distribution=pd.DataFrame(),
            model_metrics=pd.DataFrame(),
            signal_metrics=pd.DataFrame(),
            uplift=pd.DataFrame(),
            stable_candidates=pd.DataFrame(),
            feature_importance=pd.DataFrame(),
            samples=pd.DataFrame(),
            failures=pd.DataFrame(),
            causal_audit=_causal_audit(config),
            decision=decision,
            reason=reason,
            champion=None,
            config=config,
        )
        return StateContextAblationResult(decision, config.report_path, None)

    base_paths = [
        path
        for path in list_cached_years(LONG_CONTEXT_BASE_CONFIG)
        if 2023 <= int(path.name[-4:]) <= 2025
    ]
    available_years = {int(path.name[-4:]) for path in base_paths}
    if available_years != {2023, 2024, 2025}:
        decision = "BLOCKED_BASE_CACHE"
        reason = (
            "R03.4只复用现有R03.2基础缓存以保持2026封存；缺少2023/2024/2025缓存，"
            f"当前可用={sorted(available_years)}。请先完成R03.2缓存。"
        )
        write_reports(
            config.report_path,
            manifest={"stage": STAGE_ID, "name": STAGE_NAME, "config": config.to_dict()},
            preflight=preflight,
            target_distribution=pd.DataFrame(),
            model_metrics=pd.DataFrame(),
            signal_metrics=pd.DataFrame(),
            uplift=pd.DataFrame(),
            stable_candidates=pd.DataFrame(),
            feature_importance=pd.DataFrame(),
            samples=pd.DataFrame(),
            failures=pd.DataFrame(),
            causal_audit=_causal_audit(config),
            decision=decision,
            reason=reason,
            champion=None,
            config=config,
        )
        return StateContextAblationResult(decision, config.report_path, None)
    state_paths = build_state_caches(
        state_loader,
        DEFAULT_MARKET_STATE_CONTINUITY_CONFIG,
        force_rebuild=force_rebuild_state_cache,
        progress=progress,
    )
    outcome_paths = build_outcome_caches(
        base_paths,
        config,
        force_rebuild=force_rebuild_outcomes,
        progress=progress,
    )

    metric_rows: list[dict[str, object]] = []
    signal_rows: list[dict[str, object]] = []
    importance_rows: list[dict[str, object]] = []
    sample_parts: list[pd.DataFrame] = []
    failures: list[dict[str, object]] = []
    folds = default_ablation_folds(config)
    reporter = ProgressReporter("[R03.4 ablation] jobs", len(folds) * len(config.variants), every=1, enabled=progress)
    job = 0

    for fold in folds:
        fit = collect_ablation_period_data(
            base_paths, state_paths, outcome_paths, start=fold.fit_start, end=fold.fit_end, config=config
        )
        calibration = collect_ablation_period_data(
            base_paths,
            state_paths,
            outcome_paths,
            start=fold.calibration_start,
            end=fold.calibration_end,
            config=config,
        )
        test = collect_ablation_period_data(
            base_paths, state_paths, outcome_paths, start=fold.test_start, end=fold.test_end, config=config
        )
        try:
            fit, calibration, test = _attach_activity_probabilities(
                fold, fit, calibration, test, state_paths, base_paths
            )
        except Exception as exc:
            failures.append(
                {
                    "fold_id": fold.fold_id,
                    "variant": "activity_persistence_feature",
                    "error": f"{type(exc).__name__}: {exc}",
                }
            )

        for variant in config.variants:
            job += 1
            try:
                model, columns, metadata = fit_opening_value_model(variant, fit, config)
                metrics, signals, samples = evaluate_opening_value_model(
                    fold_id=fold.fold_id,
                    variant=variant,
                    model=model,
                    calibration=calibration,
                    test=test,
                    config=config,
                )
                metrics.update(metadata)
                metric_rows.append(metrics)
                signal_rows.extend(signals)
                importance_rows.extend(_importance(model, columns, fold.fold_id, variant))
                if not samples.empty:
                    sample_parts.append(samples)
            except Exception as exc:
                failures.append(
                    {
                        "fold_id": fold.fold_id,
                        "variant": variant,
                        "error": f"{type(exc).__name__}: {exc}",
                    }
                )
            reporter.update(job)
    reporter.close()

    metrics = pd.DataFrame(metric_rows)
    signals = pd.DataFrame(signal_rows)
    uplift = build_uplift_table(metrics, signals)
    stable = select_stable_uplift(uplift, config)
    passed = stable.loc[stable["passes"]] if not stable.empty else pd.DataFrame()
    champion = passed.iloc[0].to_dict() if not passed.empty else None
    if champion is not None:
        decision = "PASS_STATE_CONTEXT_UPLIFT"
        reason = "至少一个状态上下文版本在2024和2025都提高方向排序与90%阈值后的成本后平均收益。"
    elif not metrics.empty:
        decision = "FAIL_NO_STABLE_STATE_CONTEXT_UPLIFT"
        reason = "状态上下文未能在2024和2025同时稳定超过相同开仓价值模型基线。"
    else:
        decision = "FAIL_NO_VALID_MODELS"
        reason = "所有模型任务失败，不能判断状态上下文增量。"

    samples = pd.concat(sample_parts, ignore_index=True) if sample_parts else pd.DataFrame()
    if len(samples) > 100_000:
        samples = samples.iloc[np.linspace(0, len(samples) - 1, 100_000, dtype=np.int64)].reset_index(drop=True)
    importance = pd.DataFrame(importance_rows)
    if not importance.empty:
        importance = importance.sort_values(
            ["fold_id", "variant", "side", "importance"],
            ascending=[True, True, True, False],
            kind="stable",
        ).groupby(["fold_id", "variant", "side"], as_index=False).head(100)

    write_reports(
        config.report_path,
        manifest={
            "stage": STAGE_ID,
            "name": STAGE_NAME,
            "config": config.to_dict(),
            "folds": [fold.to_dict() for fold in folds],
        },
        preflight=preflight,
        target_distribution=_target_distribution(outcome_paths, config),
        model_metrics=metrics,
        signal_metrics=signals,
        uplift=uplift,
        stable_candidates=stable,
        feature_importance=importance,
        samples=samples,
        failures=pd.DataFrame(failures),
        causal_audit=_causal_audit(config),
        decision=decision,
        reason=reason,
        champion=champion,
        config=config,
    )
    return StateContextAblationResult(decision, config.report_path, champion)
